from enum import Enum


class Mnemonics(Enum):
    """
    libr/asm/d/x86.c: static const struct kv kvs[]
    shlr/capstone/arch/X86
    """
    _ALL = {
        "aaa",
        "aad",
        "aam",
        "aas",
        "adc",
        "adcx",
        "add",
        "addpd",
        "addps",
        "addsd",
        "addss",
        "addsubpd",
        "addsubps",
        "adox",
        "aesdec",
        "aesdeclast",
        "aesenc",
        "aesenclast",
        "aesimc",
        "aeskeygenassist",
        "and",
        "andn",
        "andnpd",
        "andnps",
        "andpd",
        "andps",
        "arpl",
        "bextr",
        "blcfill",
        "blci",
        "blcic",
        "blcmsk",
        "blcs",
        "blendpd",
        "blendps",
        "blendvpd",
        "blendvps",
        "blsfill",
        "blsi",
        "blsic",
        "blsmsk",
        "blsr",
        "bndcl",
        "bndcn",
        "bndcu",
        "bndldx",
        "bndmk",
        "bndmov",
        "bndstx",
        "bound",
        "bsf",
        "bsr",
        "bswap",
        "bt",
        "btc",
        "btr",
        "bts",
        "bzhi",
        "call",
        "callf",
        "cbw",
        "cdq",
        "cdqe",
        "clac",
        "clc",
        "cld",
        "cldemote",
        "clflush",
        "clflushopt",
        "clgi",
        "cli",
        "clrssbsy",
        "clts",
        "clwb",
        "clzero",
        "cmc",
        "cmova",
        "cmovae",
        "cmovb",
        "cmovbe",
        "cmovc",
        "cmove",
        "cmovg",
        "cmovge",
        "cmovl",
        "cmovle",
        "cmovna",
        "cmovnae",
        "cmovnb",
        "cmovnbe",
        "cmovnc",
        "cmovne",
        "cmovng",
        "cmovnge",
        "cmovnl",
        "cmovnle",
        "cmovno",
        "cmovnp",
        "cmovns",
        "cmovnz",
        "cmovo",
        "cmovp",
        "cmovpe",
        "cmovpo",
        "cmovs",
        "cmovz",
        "cmp",
        "cmpeqpd",
        "cmpeqps",
        "cmpeqsd",
        "cmpeqss",
        "cmplepd",
        "cmpleps",
        "cmplesd",
        "cmpless",
        "cmpltpd",
        "cmpltps",
        "cmpltsd",
        "cmpltss",
        "cmpneqpd",
        "cmpneqps",
        "cmpneqsd",
        "cmpneqss",
        "cmpnlepd",
        "cmpnleps",
        "cmpnlesd",
        "cmpnless",
        "cmpnltpd",
        "cmpnltps",
        "cmpnltsd",
        "cmpnltss",
        "cmpordpd",
        "cmpordps",
        "cmpordsd",
        "cmpordss",
        "cmppd",
        "cmpps",
        "cmps",
        "cmpsb",
        "cmpsd",
        "cmpsq",
        "cmpss",
        "cmpsw",
        "cmpunordpd",
        "cmpunordps",
        "cmpunordsd",
        "cmpunordss",
        "cmpxchg",
        "cmpxchg16b",
        "cmpxchg8b",
        "comisd",
        "comiss",
        "comvle",
        "cpu_read",
        "cpu_write",
        "cpuid",
        "cqo",
        "crc32",
        "cvtdq2pd",
        "cvtdq2ps",
        "cvtpd2dq",
        "cvtpd2pi",
        "cvtpd2ps",
        "cvtpi2pd",
        "cvtpi2ps",
        "cvtps2dq",
        "cvtps2pd",
        "cvtps2pi",
        "cvtsd2si",
        "cvtsd2ss",
        "cvtsi2sd",
        "cvtsi2ss",
        "cvtss2sd",
        "cvtss2si",
        "cvttpd2dq",
        "cvttpd2pi",
        "cvttps2dq",
        "cvttps2pi",
        "cvttsd2si",
        "cvttss2si",
        "cwd",
        "cwde",
        "daa",
        "das",
        "data16",
        "dec",
        "div",
        "divpd",
        "divps",
        "divsd",
        "divss",
        "dmint",
        "dppd",
        "dpps",
        "emms",
        "encls",
        "enclu",
        "enclv",
        "endbr32",
        "endbr64",
        "enter",
        "extractps",
        "extrq",
        "f2xm1",
        "fabs",
        "fadd",
        "faddp",
        "fbld",
        "fbstp",
        "fchs",
        "fclex",
        "fcmovb",
        "fcmovbe",
        "fcmove",
        "fcmovnb",
        "fcmovnbe",
        "fcmovne",
        "fcmovnp",
        "fcmovnu",
        "fcmovu",
        "fcom",
        "fcomi",
        "fcomip",
        "fcomp",
        "fcompi",
        "fcompp",
        "fcos",
        "fdecstp",
        "fdisi",
        "fdisi8087_nop",
        "fdiv",
        "fdivp",
        "fdivr",
        "fdivrp",
        "femms",
        "feni",
        "feni8087_nop",
        "ffree",
        "ffreep",
        "fiadd",
        "ficom",
        "ficomp",
        "fidiv",
        "fidivr",
        "fild",
        "fimul",
        "fincstp",
        "finit",
        "fist",
        "fistp",
        "fisttp",
        "fisub",
        "fisubr",
        "fld",
        "fld1",
        "fldcw",
        "fldenv",
        "fldl2e",
        "fldl2t",
        "fldlg2",
        "fldln2",
        "fldpi",
        "fldz",
        "fmul",
        "fmulp",
        "fnclex",
        "fndisi",
        "fneni",
        "fninit",
        "fnop",
        "fnsave",
        "fnsetpm",
        "fnstcw",
        "fnstenv",
        "fnstsw",
        "fpatan",
        "fprem",
        "fprem1",
        "fptan",
        "frndint",
        "frstor",
        "fsave",
        "fscale",
        "fsetpm",
        "fsin",
        "fsincos",
        "fsqrt",
        "fst",
        "fstcw",
        "fstenv",
        "fstp",
        "fstpnce",
        "fstsw",
        "fsub",
        "fsubp",
        "fsubr",
        "fsubrp",
        "ftst",
        "fucom",
        "fucomi",
        "fucomip",
        "fucomp",
        "fucompi",
        "fucompp",
        "fwait",
        "fxam",
        "fxch",
        "fxrstor",
        "fxrstor64",
        "fxsave",
        "fxsave64",
        "fxtract",
        "fyl2x",
        "fyl2xp1",
        "getsec",
        "gf2p8affineinvqb",
        "gf2p8affineqb",
        "gf2p8mulb",
        "haddpd",
        "haddps",
        "hint_nop",
        "hlt",
        "hsubpd",
        "hsubps",
        "icebp",
        "idiv",
        "imul",
        "in",
        "inc",
        "incsspd",
        "incsspq",
        "ins",
        "insb",
        "insd",
        "insertps",
        "insertq",
        "insw",
        "int",
        "int01",
        "int03",
        "int1",
        "int3",
        "into",
        "invd",
        "invept",
        "invlpg",
        "invlpga",
        "invpcid",
        "invvpid",
        "iret",
        "iretd",
        "iretq",
        "iretw",
        "ja",
        "jae",
        "jb",
        "jbe",
        "jc",
        "jcxz",
        "je",
        "jecxz",
        "jg",
        "jge",
        "jl",
        "jle",
        "jmp",
        "jmpe",
        "jmpf",
        "jna",
        "jnae",
        "jnb",
        "jnbe",
        "jnc",
        "jne",
        "jng",
        "jnge",
        "jnl",
        "jnle",
        "jno",
        "jnp",
        "jns",
        "jnz",
        "jo",
        "jp",
        "jpe",
        "jpo",
        "jrcxz",
        "js",
        "jz",
        "kaddb",
        "kaddd",
        "kaddq",
        "kaddw",
        "kandb",
        "kandd",
        "kandnb",
        "kandnd",
        "kandnq",
        "kandnw",
        "kandq",
        "kandw",
        "kmovb",
        "kmovd",
        "kmovq",
        "kmovw",
        "knotb",
        "knotd",
        "knotq",
        "knotw",
        "korb",
        "kord",
        "korq",
        "kortestb",
        "kortestd",
        "kortestq",
        "kortestw",
        "korw",
        "kshiftlb",
        "kshiftld",
        "kshiftlq",
        "kshiftlw",
        "kshiftrb",
        "kshiftrd",
        "kshiftrq",
        "kshiftrw",
        "ktestb",
        "ktestd",
        "ktestq",
        "ktestw",
        "kunpckbw",
        "kunpckdq",
        "kunpckwd",
        "kxnorb",
        "kxnord",
        "kxnorq",
        "kxnorw",
        "kxorb",
        "kxord",
        "kxorq",
        "kxorw",
        "lahf",
        "lar",
        "lcall",
        "lddqu",
        "ldmxcsr",
        "lds",
        "lea",
        "leave",
        "les",
        "lfence",
        "lfs",
        "lgdt",
        "lgs",
        "lidt",
        "ljmp",
        "lldt",
        "llwpcb",
        "lmsw",
        "loadall",
        "loadalld",
        "lock",
        "lods",
        "lodsb",
        "lodsd",
        "lodsq",
        "lodsw",
        "loop",
        "loope",
        "loopne",
        "loopnz",
        "loopz",
        "lsl",
        "lss",
        "ltr",
        "lwpins",
        "lwpval",
        "lzcnt",
        "maskmovdqu",
        "maskmovq",
        "maxpd",
        "maxps",
        "maxsd",
        "maxss",
        "mfence",
        "minpd",
        "minps",
        "minsd",
        "minss",
        "monitor",
        "monitorx",
        "montmul",
        "mov",
        "movabs",
        "movapd",
        "movaps",
        "movbe",
        "movd",
        "movddup",
        "movdir64b",
        "movdiri",
        "movdmovq",
        "movdq2q",
        "movdqa",
        "movdqu",
        "movhlps",
        "movhpd",
        "movhps",
        "movlhps",
        "movlpd",
        "movlps",
        "movmskpd",
        "movmskps",
        "movntdq",
        "movntdqa",
        "movnti",
        "movntpd",
        "movntps",
        "movntq",
        "movntsd",
        "movntss",
        "movq",
        "movq2dq",
        "movs",
        "movsb",
        "movsd",
        "movshdup",
        "movsldup",
        "movsq",
        "movss",
        "movsw",
        "movsx",
        "movsxd",
        "movupd",
        "movups",
        "movzx",
        "mpsadbw",
        "mul",
        "mulpd",
        "mulps",
        "mulsd",
        "mulss",
        "mulx",
        "mwait",
        "mwaitx",
        "neg",
        "nop",
        "not",
        "or",
        "orpd",
        "orps",
        "out",
        "outs",
        "outsb",
        "outsd",
        "outsw",
        "pabsb",
        "pabsd",
        "pabsq",
        "pabsw",
        "packssdw",
        "packsswb",
        "packusdw",
        "packuswb",
        "paddb",
        "paddd",
        "paddq",
        "paddsb",
        "paddsiw",
        "paddsw",
        "paddusb",
        "paddusw",
        "paddw",
        "palignr",
        "pand",
        "pandn",
        "pause",
        "paveb",
        "pavgb",
        "pavgusb",
        "pavgw",
        "pblendvb",
        "pblendw",
        "pclmulhqhqdq",
        "pclmulhqlqdq",
        "pclmullqhqdq",
        "pclmullqlqdq",
        "pclmulqdq",
        "pcmpeqb",
        "pcmpeqd",
        "pcmpeqq",
        "pcmpeqw",
        "pcmpestri",
        "pcmpestrm",
        "pcmpgtb",
        "pcmpgtd",
        "pcmpgtq",
        "pcmpgtw",
        "pcmpistri",
        "pcmpistrm",
        "pconfig",
        "pdep",
        "pdistib",
        "pext",
        "pextrb",
        "pextrd",
        "pextrq",
        "pextrw",
        "pf2id",
        "pf2iw",
        "pfacc",
        "pfadd",
        "pfcmpeq",
        "pfcmpge",
        "pfcmpgt",
        "pfmax",
        "pfmin",
        "pfmul",
        "pfnacc",
        "pfpnacc",
        "pfrcp",
        "pfrcpit1",
        "pfrcpit2",
        "pfrcpv",
        "pfrsqit1",
        "pfrsqrt",
        "pfrsqrtv",
        "pfsub",
        "pfsubr",
        "phaddd",
        "phaddsw",
        "phaddw",
        "phminposuw",
        "phsubd",
        "phsubsw",
        "phsubw",
        "pi2fd",
        "pi2fw",
        "pinsrb",
        "pinsrd",
        "pinsrq",
        "pinsrw",
        "pmachriw",
        "pmaddubsw",
        "pmaddwd",
        "pmagw",
        "pmaxsb",
        "pmaxsd",
        "pmaxsq",
        "pmaxsw",
        "pmaxub",
        "pmaxud",
        "pmaxuq",
        "pmaxuw",
        "pminsb",
        "pminsd",
        "pminsq",
        "pminsw",
        "pminub",
        "pminud",
        "pminuq",
        "pminuw",
        "pmovmskb",
        "pmovsx",
        "pmovsxbd",
        "pmovsxbq",
        "pmovsxbw",
        "pmovsxdq",
        "pmovsxwd",
        "pmovsxwq",
        "pmovzx",
        "pmovzxbd",
        "pmovzxbq",
        "pmovzxbw",
        "pmovzxdq",
        "pmovzxwd",
        "pmovzxwq",
        "pmuldq",
        "pmulhriw",
        "pmulhrsw",
        "pmulhrw",
        "pmulhrwa",
        "pmulhrwc",
        "pmulhuw",
        "pmulhw",
        "pmulld",
        "pmullq",
        "pmullw",
        "pmuludq",
        "pmvgezb",
        "pmvlzb",
        "pmvnzb",
        "pmvzb",
        "pop",
        "popa",
        "popad",
        "popal",
        "popaw",
        "popcnt",
        "popf",
        "popfd",
        "popfl",
        "popfq",
        "popfw",
        "por",
        "prefetch",
        "prefetchnta",
        "prefetcht0",
        "prefetcht1",
        "prefetcht2",
        "prefetchw",
        "prefetchwt1",
        "prold",
        "prolq",
        "prolvd",
        "prolvq",
        "prord",
        "prorq",
        "prorvd",
        "prorvq",
        "psadbw",
        "pshufb",
        "pshufd",
        "pshufhw",
        "pshuflw",
        "pshufw",
        "psignb",
        "psignd",
        "psignw",
        "pslld",
        "pslldq",
        "psllq",
        "psllw",
        "psrad",
        "psraq",
        "psraw",
        "psrld",
        "psrldq",
        "psrlq",
        "psrlw",
        "psubb",
        "psubd",
        "psubq",
        "psubsb",
        "psubsiw",
        "psubsw",
        "psubusb",
        "psubusw",
        "psubw",
        "pswapd",
        "ptest",
        "ptwrite",
        "punpckhbw",
        "punpckhdq",
        "punpckhqdq",
        "punpckhwd",
        "punpcklbw",
        "punpckldq",
        "punpcklqdq",
        "punpcklwd",
        "push",
        "pusha",
        "pushad",
        "pushal",
        "pushaw",
        "pushf",
        "pushfd",
        "pushfl",
        "pushfq",
        "pushfw",
        "pxor",
        "pxord",
        "pxorq",
        "rcl",
        "rcpps",
        "rcpss",
        "rcr",
        "rdfsbase",
        "rdgsbase",
        "rdm",
        "rdmsr",
        "rdpid",
        "rdpkru",
        "rdpmc",
        "rdrand",
        "rdseed",
        "rdshr",
        "rdsspd",
        "rdsspq",
        "rdtsc",
        "rdtscp",
        "rep",
        "repe",
        "repne",
        "repnz",
        "repz",
        "ret",
        "retf",
        "retfq",
        "retn",
        "rex",
        "rex.b",
        "rex.r",
        "rex.rb",
        "rex.rx",
        "rex.rxb",
        "rex.w",
        "rex.wb",
        "rex.wr",
        "rex.wrb",
        "rex.wrx",
        "rex.wrxb",
        "rex.wx",
        "rex.wxb",
        "rex.x",
        "rex.xb",
        "rex64",
        "rol",
        "ror",
        "rorx",
        "roundpd",
        "roundps",
        "roundsd",
        "roundss",
        "rsdc",
        "rsldt",
        "rsm",
        "rsqrtps",
        "rsqrtss",
        "rstorssp",
        "rsts",
        "rtdsc",
        "sahf",
        "sal",
        "salc",
        "sar",
        "sarx",
        "saveprevssp",
        "sbb",
        "scas",
        "scasb",
        "scasd",
        "scasq",
        "scasw",
        "seta",
        "setae",
        "setb",
        "setbe",
        "setc",
        "sete",
        "setg",
        "setge",
        "setl",
        "setle",
        "setna",
        "setnae",
        "setnb",
        "setnbe",
        "setnc",
        "setne",
        "setng",
        "setnge",
        "setnl",
        "setnle",
        "setno",
        "setnp",
        "setns",
        "setnz",
        "seto",
        "setp",
        "setpe",
        "setpo",
        "sets",
        "setssbsy",
        "setz",
        "sfence",
        "sgdt",
        "sha1msg1",
        "sha1msg2",
        "sha1nexte",
        "sha1rnds4",
        "sha256msg1",
        "sha256msg2",
        "sha256rnds2",
        "shl",
        "shld",
        "shlx",
        "shr",
        "shrd",
        "shrx",
        "shufpd",
        "shufps",
        "sidt",
        "skinit",
        "sldt",
        "slwpcb",
        "smint",
        "smsw",
        "sqrtpd",
        "sqrtps",
        "sqrtsd",
        "sqrtss",
        "ss",
        "stac",
        "stc",
        "std",
        "stgi",
        "sti",
        "stmxcsr",
        "stos",
        "stosb",
        "stosd",
        "stosq",
        "stosw",
        "str",
        "sub",
        "subpd",
        "subps",
        "subsd",
        "subss",
        "svdc",
        "svldt",
        "svts",
        "swapgs",
        "syscall",
        "sysenter",
        "sysexit",
        "sysexitq",
        "sysret",
        "sysretq",
        "t1mskc",
        "test",
        "tpause",
        "tzcnt",
        "tzmsk",
        "ucomisd",
        "ucomiss",
        "ud0",
        "ud1",
        "ud2",
        "ud2a",
        "umonitor",
        "umwait",
        "unpckhpd",
        "unpckhps",
        "unpcklpd",
        "unpcklps",
        "v4fmaddps",
        "v4fmaddss",
        "v4fnmaddps",
        "v4fnmaddss",
        "vaddpd",
        "vaddps",
        "vaddsd",
        "vaddss",
        "vaddsubpd",
        "vaddsubps",
        "vaesdec",
        "vaesdeclast",
        "vaesenc",
        "vaesenclast",
        "vaesimc",
        "vaeskeygenassist",
        "valignd",
        "valignq",
        "vandnpd",
        "vandnps",
        "vandpd",
        "vandps",
        "vblendmpd",
        "vblendmps",
        "vblendpd",
        "vblendps",
        "vblendvpd",
        "vblendvps",
        "vbroadcast",
        "vbroadcastf128",
        "vbroadcastf32x2",
        "vbroadcastf32x4",
        "vbroadcastf32x8",
        "vbroadcastf64x2",
        "vbroadcastf64x4",
        "vbroadcasti128",
        "vbroadcasti32x2",
        "vbroadcasti32x4",
        "vbroadcasti32x8",
        "vbroadcasti64x2",
        "vbroadcasti64x4",
        "vbroadcastsd",
        "vbroadcastss",
        "vcmp",
        "vcmpeq_ospd",
        "vcmpeq_osps",
        "vcmpeq_ossd",
        "vcmpeq_osss",
        "vcmpeq_uqpd",
        "vcmpeq_uqps",
        "vcmpeq_uqsd",
        "vcmpeq_uqss",
        "vcmpeq_uspd",
        "vcmpeq_usps",
        "vcmpeq_ussd",
        "vcmpeq_usss",
        "vcmpeqpd",
        "vcmpeqps",
        "vcmpeqsd",
        "vcmpeqss",
        "vcmpfalse_oqpd",
        "vcmpfalse_oqps",
        "vcmpfalse_oqsd",
        "vcmpfalse_oqss",
        "vcmpfalse_ospd",
        "vcmpfalse_osps",
        "vcmpfalse_ossd",
        "vcmpfalse_osss",
        "vcmpfalsepd",
        "vcmpfalseps",
        "vcmpfalsesd",
        "vcmpfalsess",
        "vcmpge_oqpd",
        "vcmpge_oqps",
        "vcmpge_oqsd",
        "vcmpge_oqss",
        "vcmpge_ospd",
        "vcmpge_osps",
        "vcmpge_ossd",
        "vcmpge_osss",
        "vcmpgepd",
        "vcmpgeps",
        "vcmpgesd",
        "vcmpgess",
        "vcmpgt_oqpd",
        "vcmpgt_oqps",
        "vcmpgt_oqsd",
        "vcmpgt_oqss",
        "vcmpgt_ospd",
        "vcmpgt_osps",
        "vcmpgt_ossd",
        "vcmpgt_osss",
        "vcmpgtpd",
        "vcmpgtps",
        "vcmpgtsd",
        "vcmpgtss",
        "vcmple_oqpd",
        "vcmple_oqps",
        "vcmple_oqsd",
        "vcmple_oqss",
        "vcmple_ospd",
        "vcmple_osps",
        "vcmple_ossd",
        "vcmple_osss",
        "vcmplepd",
        "vcmpleps",
        "vcmplesd",
        "vcmpless",
        "vcmplt_oqpd",
        "vcmplt_oqps",
        "vcmplt_oqsd",
        "vcmplt_oqss",
        "vcmplt_ospd",
        "vcmplt_osps",
        "vcmplt_ossd",
        "vcmplt_osss",
        "vcmpltpd",
        "vcmpltps",
        "vcmpltsd",
        "vcmpltss",
        "vcmpneq_oqpd",
        "vcmpneq_oqps",
        "vcmpneq_oqsd",
        "vcmpneq_oqss",
        "vcmpneq_ospd",
        "vcmpneq_osps",
        "vcmpneq_ossd",
        "vcmpneq_osss",
        "vcmpneq_uqpd",
        "vcmpneq_uqps",
        "vcmpneq_uqsd",
        "vcmpneq_uqss",
        "vcmpneq_uspd",
        "vcmpneq_usps",
        "vcmpneq_ussd",
        "vcmpneq_usss",
        "vcmpneqpd",
        "vcmpneqps",
        "vcmpneqsd",
        "vcmpneqss",
        "vcmpnge_uqpd",
        "vcmpnge_uqps",
        "vcmpnge_uqsd",
        "vcmpnge_uqss",
        "vcmpnge_uspd",
        "vcmpnge_usps",
        "vcmpnge_ussd",
        "vcmpnge_usss",
        "vcmpngepd",
        "vcmpngeps",
        "vcmpngesd",
        "vcmpngess",
        "vcmpngt_uqpd",
        "vcmpngt_uqps",
        "vcmpngt_uqsd",
        "vcmpngt_uqss",
        "vcmpngt_uspd",
        "vcmpngt_usps",
        "vcmpngt_ussd",
        "vcmpngt_usss",
        "vcmpngtpd",
        "vcmpngtps",
        "vcmpngtsd",
        "vcmpngtss",
        "vcmpnle_uqpd",
        "vcmpnle_uqps",
        "vcmpnle_uqsd",
        "vcmpnle_uqss",
        "vcmpnle_uspd",
        "vcmpnle_usps",
        "vcmpnle_ussd",
        "vcmpnle_usss",
        "vcmpnlepd",
        "vcmpnleps",
        "vcmpnlesd",
        "vcmpnless",
        "vcmpnlt_uqpd",
        "vcmpnlt_uqps",
        "vcmpnlt_uqsd",
        "vcmpnlt_uqss",
        "vcmpnlt_uspd",
        "vcmpnlt_usps",
        "vcmpnlt_ussd",
        "vcmpnlt_usss",
        "vcmpnltpd",
        "vcmpnltps",
        "vcmpnltsd",
        "vcmpnltss",
        "vcmpord_qpd",
        "vcmpord_qps",
        "vcmpord_qsd",
        "vcmpord_qss",
        "vcmpord_spd",
        "vcmpord_sps",
        "vcmpord_ssd",
        "vcmpord_sss",
        "vcmpordpd",
        "vcmpordps",
        "vcmpordsd",
        "vcmpordss",
        "vcmppd",
        "vcmpps",
        "vcmpsd",
        "vcmpss",
        "vcmptrue_uqpd",
        "vcmptrue_uqps",
        "vcmptrue_uqsd",
        "vcmptrue_uqss",
        "vcmptrue_uspd",
        "vcmptrue_usps",
        "vcmptrue_ussd",
        "vcmptrue_usss",
        "vcmptruepd",
        "vcmptrueps",
        "vcmptruesd",
        "vcmptruess",
        "vcmpunord_qpd",
        "vcmpunord_qps",
        "vcmpunord_qsd",
        "vcmpunord_qss",
        "vcmpunord_spd",
        "vcmpunord_sps",
        "vcmpunord_ssd",
        "vcmpunord_sss",
        "vcmpunordpd",
        "vcmpunordps",
        "vcmpunordsd",
        "vcmpunordss",
        "vcomisd",
        "vcomiss",
        "vcompresspd",
        "vcompressps",
        "vcvtdq2pd",
        "vcvtdq2ps",
        "vcvtpd2dq",
        "vcvtpd2dqx",
        "vcvtpd2dqy",
        "vcvtpd2ps",
        "vcvtpd2psx",
        "vcvtpd2psy",
        "vcvtpd2qq",
        "vcvtpd2udq",
        "vcvtpd2uqq",
        "vcvtph2ps",
        "vcvtps2dq",
        "vcvtps2pd",
        "vcvtps2ph",
        "vcvtps2qq",
        "vcvtps2udq",
        "vcvtps2uqq",
        "vcvtqq2pd",
        "vcvtqq2ps",
        "vcvtsd2si",
        "vcvtsd2sil",
        "vcvtsd2siq",
        "vcvtsd2ss",
        "vcvtsd2usi",
        "vcvtsi2sd",
        "vcvtsi2sdl",
        "vcvtsi2sdq",
        "vcvtsi2ss",
        "vcvtsi2ssl",
        "vcvtsi2ssq",
        "vcvtss2sd",
        "vcvtss2si",
        "vcvtss2sil",
        "vcvtss2siq",
        "vcvtss2usi",
        "vcvttpd2dq",
        "vcvttpd2dqx",
        "vcvttpd2dqy",
        "vcvttpd2qq",
        "vcvttpd2udq",
        "vcvttpd2uqq",
        "vcvttps2dq",
        "vcvttps2qq",
        "vcvttps2udq",
        "vcvttps2uqq",
        "vcvttsd2si",
        "vcvttsd2sil",
        "vcvttsd2siq",
        "vcvttsd2usi",
        "vcvttss2si",
        "vcvttss2sil",
        "vcvttss2siq",
        "vcvttss2usi",
        "vcvtudq2pd",
        "vcvtudq2ps",
        "vcvtuqq2pd",
        "vcvtuqq2ps",
        "vcvtusi2sd",
        "vcvtusi2ss",
        "vdbpsadbw",
        "vdivpd",
        "vdivps",
        "vdivsd",
        "vdivss",
        "vdppd",
        "vdpps",
        "verr",
        "verw",
        "vexp2pd",
        "vexp2ps",
        "vexpandpd",
        "vexpandps",
        "vextractf128",
        "vextractf32x4",
        "vextractf32x8",
        "vextractf64x2",
        "vextractf64x4",
        "vextracti128",
        "vextracti32x4",
        "vextracti32x8",
        "vextracti64x2",
        "vextracti64x4",
        "vextractps",
        "vfixupimmpd",
        "vfixupimmps",
        "vfixupimmsd",
        "vfixupimmss",
        "vfmadd123pd",
        "vfmadd123ps",
        "vfmadd123sd",
        "vfmadd123ss",
        "vfmadd132pd",
        "vfmadd132ps",
        "vfmadd132sd",
        "vfmadd132ss",
        "vfmadd213pd",
        "vfmadd213ps",
        "vfmadd213sd",
        "vfmadd213ss",
        "vfmadd231pd",
        "vfmadd231ps",
        "vfmadd231sd",
        "vfmadd231ss",
        "vfmadd312pd",
        "vfmadd312ps",
        "vfmadd312sd",
        "vfmadd312ss",
        "vfmadd321pd",
        "vfmadd321ps",
        "vfmadd321sd",
        "vfmadd321ss",
        "vfmaddpd",
        "vfmaddps",
        "vfmaddsd",
        "vfmaddss",
        "vfmaddsub123pd",
        "vfmaddsub123ps",
        "vfmaddsub132pd",
        "vfmaddsub132ps",
        "vfmaddsub213pd",
        "vfmaddsub213ps",
        "vfmaddsub231pd",
        "vfmaddsub231ps",
        "vfmaddsub312pd",
        "vfmaddsub312ps",
        "vfmaddsub321pd",
        "vfmaddsub321ps",
        "vfmaddsubpd",
        "vfmaddsubps",
        "vfmsub123pd",
        "vfmsub123ps",
        "vfmsub123sd",
        "vfmsub123ss",
        "vfmsub132pd",
        "vfmsub132ps",
        "vfmsub132sd",
        "vfmsub132ss",
        "vfmsub213pd",
        "vfmsub213ps",
        "vfmsub213sd",
        "vfmsub213ss",
        "vfmsub231pd",
        "vfmsub231ps",
        "vfmsub231sd",
        "vfmsub231ss",
        "vfmsub312pd",
        "vfmsub312ps",
        "vfmsub312sd",
        "vfmsub312ss",
        "vfmsub321pd",
        "vfmsub321ps",
        "vfmsub321sd",
        "vfmsub321ss",
        "vfmsubadd123pd",
        "vfmsubadd123ps",
        "vfmsubadd132pd",
        "vfmsubadd132ps",
        "vfmsubadd213pd",
        "vfmsubadd213ps",
        "vfmsubadd231pd",
        "vfmsubadd231ps",
        "vfmsubadd312pd",
        "vfmsubadd312ps",
        "vfmsubadd321pd",
        "vfmsubadd321ps",
        "vfmsubaddpd",
        "vfmsubaddps",
        "vfmsubpd",
        "vfmsubps",
        "vfmsubsd",
        "vfmsubss",
        "vfnmadd123pd",
        "vfnmadd123ps",
        "vfnmadd123sd",
        "vfnmadd123ss",
        "vfnmadd132pd",
        "vfnmadd132ps",
        "vfnmadd132sd",
        "vfnmadd132ss",
        "vfnmadd213pd",
        "vfnmadd213ps",
        "vfnmadd213sd",
        "vfnmadd213ss",
        "vfnmadd231pd",
        "vfnmadd231ps",
        "vfnmadd231sd",
        "vfnmadd231ss",
        "vfnmadd312pd",
        "vfnmadd312ps",
        "vfnmadd312sd",
        "vfnmadd312ss",
        "vfnmadd321pd",
        "vfnmadd321ps",
        "vfnmadd321sd",
        "vfnmadd321ss",
        "vfnmaddpd",
        "vfnmaddps",
        "vfnmaddsd",
        "vfnmaddss",
        "vfnmsub123pd",
        "vfnmsub123ps",
        "vfnmsub123sd",
        "vfnmsub123ss",
        "vfnmsub132pd",
        "vfnmsub132ps",
        "vfnmsub132sd",
        "vfnmsub132ss",
        "vfnmsub213pd",
        "vfnmsub213ps",
        "vfnmsub213sd",
        "vfnmsub213ss",
        "vfnmsub231pd",
        "vfnmsub231ps",
        "vfnmsub231sd",
        "vfnmsub231ss",
        "vfnmsub312pd",
        "vfnmsub312ps",
        "vfnmsub312sd",
        "vfnmsub312ss",
        "vfnmsub321pd",
        "vfnmsub321ps",
        "vfnmsub321sd",
        "vfnmsub321ss",
        "vfnmsubpd",
        "vfnmsubps",
        "vfnmsubsd",
        "vfnmsubss",
        "vfpclasspd",
        "vfpclassps",
        "vfpclasssd",
        "vfpclassss",
        "vfrczpd",
        "vfrczps",
        "vfrczsd",
        "vfrczss",
        "vgatherdp",
        "vgatherdpd",
        "vgatherdps",
        "vgatherpf0dpd",
        "vgatherpf0dps",
        "vgatherpf0qpd",
        "vgatherpf0qps",
        "vgatherpf1dpd",
        "vgatherpf1dps",
        "vgatherpf1qpd",
        "vgatherpf1qps",
        "vgatherqp",
        "vgatherqpd",
        "vgatherqps",
        "vgetexppd",
        "vgetexpps",
        "vgetexpsd",
        "vgetexpss",
        "vgetmantpd",
        "vgetmantps",
        "vgetmantsd",
        "vgetmantss",
        "vgf2p8affineinvqb",
        "vgf2p8affineqb",
        "vgf2p8mulb",
        "vhaddpd",
        "vhaddps",
        "vhsubpd",
        "vhsubps",
        "vinsertf128",
        "vinsertf32x4",
        "vinsertf32x8",
        "vinsertf64x2",
        "vinsertf64x4",
        "vinserti128",
        "vinserti32x4",
        "vinserti32x8",
        "vinserti64x2",
        "vinserti64x4",
        "vinsertps",
        "vlddqu",
        "vldmxcsr",
        "vldqqu",
        "vmaskmov",
        "vmaskmovdqu",
        "vmaskmovpd",
        "vmaskmovps",
        "vmaxpd",
        "vmaxps",
        "vmaxsd",
        "vmaxss",
        "vmcall",
        "vmclear",
        "vmfunc",
        "vminpd",
        "vminps",
        "vminsd",
        "vminss",
        "vmlaunch",
        "vmload",
        "vmmcall",
        "vmov",
        "vmovapd",
        "vmovaps",
        "vmovd",
        "vmovddup",
        "vmovdqa",
        "vmovdqa32",
        "vmovdqa64",
        "vmovdqu",
        "vmovdqu16",
        "vmovdqu32",
        "vmovdqu64",
        "vmovdqu8",
        "vmovhlps",
        "vmovhpd",
        "vmovhps",
        "vmovlhps",
        "vmovlpd",
        "vmovlps",
        "vmovmskpd",
        "vmovmskps",
        "vmovntdq",
        "vmovntdqa",
        "vmovntpd",
        "vmovntps",
        "vmovntqq",
        "vmovq",
        "vmovqqa",
        "vmovqqu",
        "vmovsd",
        "vmovshdup",
        "vmovsldup",
        "vmovss",
        "vmovupd",
        "vmovups",
        "vmpsadbw",
        "vmptrld",
        "vmptrst",
        "vmread",
        "vmresume",
        "vmrun",
        "vmsave",
        "vmulpd",
        "vmulps",
        "vmulsd",
        "vmulss",
        "vmwrite",
        "vmxoff",
        "vmxon",
        "vorpd",
        "vorps",
        "vp4dpwssd",
        "vp4dpwssds",
        "vpabs",
        "vpabsb",
        "vpabsd",
        "vpabsq",
        "vpabsw",
        "vpackss",
        "vpackssdw",
        "vpacksswb",
        "vpackusdw",
        "vpackuswb",
        "vpadd",
        "vpaddb",
        "vpaddd",
        "vpaddq",
        "vpadds",
        "vpaddsb",
        "vpaddsw",
        "vpaddus",
        "vpaddusb",
        "vpaddusw",
        "vpaddw",
        "vpalignr",
        "vpand",
        "vpandd",
        "vpandn",
        "vpandnd",
        "vpandnq",
        "vpandq",
        "vpavg",
        "vpavgb",
        "vpavgw",
        "vpblendd",
        "vpblendmb",
        "vpblendmd",
        "vpblendmq",
        "vpblendmw",
        "vpblendvb",
        "vpblendw",
        "vpbroadcast",
        "vpbroadcastb",
        "vpbroadcastd",
        "vpbroadcastmb2q",
        "vpbroadcastmw2d",
        "vpbroadcastq",
        "vpbroadcastw",
        "vpclmulhqhqdq",
        "vpclmulhqlqdq",
        "vpclmullqhqdq",
        "vpclmullqlqdq",
        "vpclmulqdq",
        "vpcmov",
        "vpcmp",
        "vpcmpb",
        "vpcmpd",
        "vpcmpeq",
        "vpcmpeqb",
        "vpcmpeqd",
        "vpcmpeqq",
        "vpcmpeqw",
        "vpcmpestri",
        "vpcmpestrm",
        "vpcmpgt",
        "vpcmpgtb",
        "vpcmpgtd",
        "vpcmpgtq",
        "vpcmpgtw",
        "vpcmpistri",
        "vpcmpistrm",
        "vpcmpq",
        "vpcmpub",
        "vpcmpud",
        "vpcmpuq",
        "vpcmpuw",
        "vpcmpw",
        "vpcom",
        "vpcomb",
        "vpcomd",
        "vpcompressb",
        "vpcompressd",
        "vpcompressq",
        "vpcompressw",
        "vpcomq",
        "vpcomub",
        "vpcomud",
        "vpcomuq",
        "vpcomuw",
        "vpcomw",
        "vpconflictd",
        "vpconflictq",
        "vpdpbusd",
        "vpdpbusds",
        "vpdpwssd",
        "vpdpwssds",
        "vperm2f128",
        "vperm2i128",
        "vpermb",
        "vpermd",
        "vpermi2b",
        "vpermi2d",
        "vpermi2pd",
        "vpermi2ps",
        "vpermi2q",
        "vpermi2w",
        "vpermil2pd",
        "vpermil2ps",
        "vpermilpd",
        "vpermilps",
        "vpermpd",
        "vpermps",
        "vpermq",
        "vpermt2b",
        "vpermt2d",
        "vpermt2pd",
        "vpermt2ps",
        "vpermt2q",
        "vpermt2w",
        "vpermw",
        "vpexpandb",
        "vpexpandd",
        "vpexpandq",
        "vpexpandw",
        "vpextr",
        "vpextrb",
        "vpextrd",
        "vpextrq",
        "vpextrw",
        "vpgatherdd",
        "vpgatherdq",
        "vpgatherqd",
        "vpgatherqq",
        "vphadd",
        "vphaddbd",
        "vphaddbq",
        "vphaddbw",
        "vphaddd",
        "vphadddq",
        "vphaddsw",
        "vphaddubd",
        "vphaddubq",
        "vphaddubw",
        "vphaddudq",
        "vphadduwd",
        "vphadduwq",
        "vphaddw",
        "vphaddwd",
        "vphaddwq",
        "vphminposuw",
        "vphsub",
        "vphsubbw",
        "vphsubd",
        "vphsubdq",
        "vphsubsw",
        "vphsubw",
        "vphsubwd",
        "vpinsr",
        "vpinsrb",
        "vpinsrd",
        "vpinsrq",
        "vpinsrw",
        "vplzcntd",
        "vplzcntq",
        "vpmacsdd",
        "vpmacsdqh",
        "vpmacsdql",
        "vpmacssdd",
        "vpmacssdqh",
        "vpmacssdql",
        "vpmacsswd",
        "vpmacssww",
        "vpmacswd",
        "vpmacsww",
        "vpmadcsswd",
        "vpmadcswd",
        "vpmadd52huq",
        "vpmadd52luq",
        "vpmaddubsw",
        "vpmaddwd",
        "vpmaskmov",
        "vpmaskmovd",
        "vpmaskmovq",
        "vpmaxs",
        "vpmaxsb",
        "vpmaxsd",
        "vpmaxsq",
        "vpmaxsw",
        "vpmaxub",
        "vpmaxud",
        "vpmaxuq",
        "vpmaxuw",
        "vpminsb",
        "vpminsd",
        "vpminsq",
        "vpminsw",
        "vpminub",
        "vpminud",
        "vpminuq",
        "vpminuw",
        "vpmovb2m",
        "vpmovd2m",
        "vpmovdb",
        "vpmovdw",
        "vpmovm2b",
        "vpmovm2d",
        "vpmovm2q",
        "vpmovm2w",
        "vpmovmskb",
        "vpmovq2m",
        "vpmovqb",
        "vpmovqd",
        "vpmovqw",
        "vpmovsdb",
        "vpmovsdw",
        "vpmovsqb",
        "vpmovsqd",
        "vpmovsqw",
        "vpmovswb",
        "vpmovsx",
        "vpmovsxbd",
        "vpmovsxbq",
        "vpmovsxbw",
        "vpmovsxdq",
        "vpmovsxwd",
        "vpmovsxwq",
        "vpmovusdb",
        "vpmovusdw",
        "vpmovusqb",
        "vpmovusqd",
        "vpmovusqw",
        "vpmovuswb",
        "vpmovw2m",
        "vpmovwb",
        "vpmovzx",
        "vpmovzxbd",
        "vpmovzxbq",
        "vpmovzxbw",
        "vpmovzxdq",
        "vpmovzxwd",
        "vpmovzxwq",
        "vpmuldq",
        "vpmulhrsw",
        "vpmulhuw",
        "vpmulhw",
        "vpmulld",
        "vpmullq",
        "vpmullw",
        "vpmultishiftqb",
        "vpmuludq",
        "vpopcntb",
        "vpopcntd",
        "vpopcntq",
        "vpopcntw",
        "vpor",
        "vpord",
        "vporq",
        "vpperm",
        "vprold",
        "vprolq",
        "vprolvd",
        "vprolvq",
        "vprord",
        "vprorq",
        "vprorvd",
        "vprorvq",
        "vprotb",
        "vprotd",
        "vprotq",
        "vprotw",
        "vpsadbw",
        "vpscatterdd",
        "vpscatterdq",
        "vpscatterqd",
        "vpscatterqq",
        "vpshab",
        "vpshad",
        "vpshaq",
        "vpshaw",
        "vpshlb",
        "vpshld",
        "vpshldd",
        "vpshldq",
        "vpshldvd",
        "vpshldvq",
        "vpshldvw",
        "vpshldw",
        "vpshlq",
        "vpshlw",
        "vpshrdd",
        "vpshrdq",
        "vpshrdvd",
        "vpshrdvq",
        "vpshrdvw",
        "vpshrdw",
        "vpshufb",
        "vpshufbitqmb",
        "vpshufd",
        "vpshufhw",
        "vpshuflw",
        "vpsign",
        "vpsignb",
        "vpsignd",
        "vpsignw",
        "vpsll",
        "vpslld",
        "vpslldq",
        "vpsllq",
        "vpsllv",
        "vpsllvd",
        "vpsllvq",
        "vpsllvw",
        "vpsllw",
        "vpsra",
        "vpsrad",
        "vpsraq",
        "vpsravd",
        "vpsravq",
        "vpsravw",
        "vpsraw",
        "vpsrl",
        "vpsrld",
        "vpsrldq",
        "vpsrlq",
        "vpsrlv",
        "vpsrlvd",
        "vpsrlvq",
        "vpsrlvw",
        "vpsrlw",
        "vpsub",
        "vpsubb",
        "vpsubd",
        "vpsubq",
        "vpsubs",
        "vpsubsb",
        "vpsubsw",
        "vpsubus",
        "vpsubusb",
        "vpsubusw",
        "vpsubw",
        "vpternlogd",
        "vpternlogq",
        "vptest",
        "vptestmb",
        "vptestmd",
        "vptestmq",
        "vptestmw",
        "vptestnmb",
        "vptestnmd",
        "vptestnmq",
        "vptestnmw",
        "vpunpckh",
        "vpunpckhbw",
        "vpunpckhdq",
        "vpunpckhqdq",
        "vpunpckhwd",
        "vpunpckl",
        "vpunpcklbw",
        "vpunpckldq",
        "vpunpcklqdq",
        "vpunpcklwd",
        "vpxor",
        "vpxord",
        "vpxorq",
        "vrangepd",
        "vrangeps",
        "vrangesd",
        "vrangess",
        "vrcp14pd",
        "vrcp14ps",
        "vrcp14sd",
        "vrcp14ss",
        "vrcp28pd",
        "vrcp28ps",
        "vrcp28sd",
        "vrcp28ss",
        "vrcpps",
        "vrcpss",
        "vreducepd",
        "vreduceps",
        "vreducesd",
        "vreducess",
        "vrndscalepd",
        "vrndscaleps",
        "vrndscalesd",
        "vrndscaless",
        "vroundpd",
        "vroundps",
        "vroundsd",
        "vroundss",
        "vrsqrt14pd",
        "vrsqrt14ps",
        "vrsqrt14sd",
        "vrsqrt14ss",
        "vrsqrt28pd",
        "vrsqrt28ps",
        "vrsqrt28sd",
        "vrsqrt28ss",
        "vrsqrtps",
        "vrsqrtss",
        "vscalefpd",
        "vscalefps",
        "vscalefsd",
        "vscalefss",
        "vscatterdpd",
        "vscatterdps",
        "vscatterpf0dpd",
        "vscatterpf0dps",
        "vscatterpf0qpd",
        "vscatterpf0qps",
        "vscatterpf1dpd",
        "vscatterpf1dps",
        "vscatterpf1qpd",
        "vscatterpf1qps",
        "vscatterqpd",
        "vscatterqps",
        "vshuff32x4",
        "vshuff64x2",
        "vshufi32x4",
        "vshufi64x2",
        "vshufpd",
        "vshufps",
        "vsqrtpd",
        "vsqrtps",
        "vsqrtsd",
        "vsqrtss",
        "vstmxcsr",
        "vsubpd",
        "vsubps",
        "vsubsd",
        "vsubss",
        "vtestp",
        "vtestpd",
        "vtestpdvtestps",
        "vtestps",
        "vucomisd",
        "vucomiss",
        "vunpckhpd",
        "vunpckhps",
        "vunpcklpd",
        "vunpcklps",
        "vxorpd",
        "vxorps",
        "vzeroall",
        "vzeroupper",
        "wait",
        "wbinvd",
        "wbnoinvd",
        "wrfsbase",
        "wrgsbase",
        "wrmsr",
        "wrpkru",
        "wrshr",
        "wrssd",
        "wrssq",
        "wrussd",
        "wrussq",
        "xabort",
        "xacquire",
        "xadd",
        "xbegin",
        "xbeginl",
        "xbeginw",
        "xchg",
        "xcryptcbc",
        "xcryptcfb",
        "xcryptctr",
        "xcryptecb",
        "xcryptofb",
        "xend",
        "xgetbv",
        "xlat",
        "xlatb",
        "xor",
        "xorpd",
        "xorps",
        "xrelease",
        "xrstor",
        "xrstor64",
        "xrstors",
        "xrstors64",
        "xsave",
        "xsave64",
        "xsavec",
        "xsavec64",
        "xsaveopt",
        "xsaveopt64",
        "xsaves",
        "xsaves64",
        "xsetbv",
        "xsha1",
        "xsha256",
        "xstore",
        "xtest"
    }
    ORACLE_INTEL_AMD__GENERAL_PURPOSE = {
        "aaa", "aad", "aam", "aas", "adc", "add", "and", "bound", "bsf", "bsr", "bswap", "bt", "btc", "btr", "bts",
        "call", "cbw", "cdq", "cdqe", "clc", "cld", "cli", "cmc", "cmova", "cmovae", "cmovb", "cmovbe", "cmovc",
        "cmove", "cmovg", "cmovge", "cmovl", "cmovna", "cmovnae", "cmovnb", "cmovnbe", "cmovnc", "cmovne", "cmovng",
        "cmovnge", "cmovnl", "cmovnle", "cmovno", "cmovnp", "cmovns", "cmovnz", "cmovo", "cmovp", "cmovpe", "cmovpo",
        "cmovs", "cmovz", "cmp", "cmps", "cmpsb", "cmpsd", "cmpsw", "cmpxchg", "cmpxchg8b", "comvle", "cpuid", "cqo",
        "cwd", "cwde", "daa", "das", "dec", "div", "enter", "idiv", "imul", "in", "inc", "ins", "insb", "insd", "insw",
        "int", "into", "invpcid", "iret", "ja", "jae", "jb", "jbe", "jc", "jcxz", "je", "jecxz", "jg", "jge", "jl",
        "jle", "jmp", "jnae", "jnb", "jnbe", "jnc", "jne", "jng", "jnge", "jnl", "jnle", "jno", "jnp", "jns", "jnz",
        "jo", "jp", "jpe", "jpo", "js", "jz", "lahf", "lds", "lea", "leave", "les", "lfs", "lgs", "lods", "lodsb",
        "lodsd", "lodsw", "loop", "loope", "loopne", "loopnz", "loopz", "lss", "mov", "movabs", "movs", "movsb",
        "movsd", "movsw", "movsx", "movzx", "mul", "neg", "nop", "not", "or", "out", "outs", "outsb", "outsd", "outsw",
        "pop", "popa", "popad", "popf", "popfl", "push", "pusha", "pushad", "pushf", "pushfl", "rcl", "rcr", "rep",
        "repe", "repne", "repnz", "repz", "ret", "rol", "ror", "sahf", "sal", "sar", "sbb", "scas", "scasb", "scasd",
        "scasw", "seta", "setae", "setb", "setbe", "setc", "sete", "setg", "setge", "setl", "setle", "setna", "setnae",
        "setnb", "setnbe", "setnc", "setne", "setng", "setnge", "setnl", "setnle", "setno", "setnp", "setns", "setnz",
        "seto", "setp", "setpe", "setpo", "sets", "setz", "shl", "shld", "shr", "shrd", "stc", "std", "sti", "stos",
        "stosb", "stosd", "stosw", "sub", "test", "ud2", "xadd", "xchg", "xlat", "xlatb", "xor"}
    ORACLE_INTEL_AMD__FLOATING_POINT = {
        "f2xm1", "fabs", "fadd", "faddp", "fbld", "fbstp", "fchs", "fclex", "fcmovb", "fcmovbe", "fcmove", "fcmovnb",
        "fcmovnbe", "fcmovne", "fcmovnu", "fcmovu", "fcom", "fcomi", "fcomip", "fcomp", "fcompp", "fcos", "fdecstp",
        "fdiv", "fdivp", "fdivr", "fdivrp", "ffree", "fiadd", "ficom", "ficomp", "fidiv", "fidivr", "fild", "fimul",
        "fincstp", "finit", "fist", "fistp", "fisub", "fisubr", "fld", "fld1", "fldcw", "fldenv", "fldl2e", "fldl2t",
        "fldlg2", "fldln2", "fldpi", "fldz", "fmul", "fmulp", "fnclex", "fninit", "fnop", "fnsave", "fnstcw", "fnstenv",
        "fnstsw", "fpatan", "fprem", "fprem1", "fptan", "frndint", "frstor", "fsave", "fscale", "fsin", "fsincos",
        "fsqrt", "fst", "fstcw", "fstenv", "fstp", "fstsw", "fsub", "fsubp", "fsubr", "fsubrp", "ftst", "fucom",
        "fucomi", "fucomip", "fucomp", "fucompp", "fwait", "fxam", "fxch", "fxtract", "fyl2x", "fyl2xp1", "wait"}
    ORACLE_INTEL_AMD__SIMD = {"fxrstor", "fxsave"}
    ORACLE_INTEL_AMD__ADX = {"adcx", "adox"}
    ORACLE_INTEL_AMD__AES = {"aesdec", "aesdeclast", "aesenc", "aesenclast", "aesimc", "aeskeygenassist"}
    ORACLE_INTEL_AMD__AVX = {
        "addpd", "addps", "addsd", "addss", "addsubpd", "addsubps", "andnpd", "andnps", "andpd", "andps", "blendpd",
        "blendps", "blendvpd", "blendvps", "cmppd", "cmpps", "cmpsd", "cmpss", "comisd", "comiss", "cvtdq2pd",
        "cvtdq2ps", "cvtpd2dq", "cvtpd2ps", "cvtps2dq", "cvtps2pd", "cvtsd2si", "cvtsd2ss", "cvtsi2sd", "cvtsi2ss",
        "cvtss2sd", "cvtss2si", "cvttpd2dq", "cvttps2dq", "cvttsd2si", "cvttss2si", "divpd", "divps", "divsd", "divss",
        "dppd", "dpps", "extractps", "haddpd", "haddps", "hsubpd", "hsubps", "insertps", "lddqu", "ldmxcsr",
        "maskmovdqu", "maxpd", "maxps", "maxsd", "maxss", "minpd", "minps", "minsd", "minss", "movapd", "movaps",
        "movddup", "movdmovq", "movdqa", "movdqu", "movhlps", "movhpd", "movhps", "movlhps", "movlpd", "movlps",
        "movmskpd", "movmskps", "movntdq", "movntdqa", "movntpd", "movntps", "movq", "movsd", "movshdup", "movsldup",
        "movss", "movupd", "movups", "mpsadbw", "mulpd", "mulps", "mulsd", "mulss", "orpd", "orps", "pabsb", "pabsd",
        "pabsq", "pabsw", "packssdw", "packsswb", "packusdw", "packuswb", "paddb", "paddd", "paddq", "paddsb", "paddsw",
        "paddusb", "paddusw", "paddw", "palignr", "pand", "pandn", "pavgb", "pavgw", "pblendvb", "pblendw", "pclmulqdq",
        "pcmpeqb", "pcmpeqd", "pcmpeqq", "pcmpeqw", "pcmpestri", "pcmpestrm", "pcmpgtb", "pcmpgtd", "pcmpgtq",
        "pcmpgtw", "pcmpistri", "pcmpistrm", "pextrb", "pextrd", "pextrq", "pextrw", "phaddd", "phaddsw", "phaddw",
        "phminposuw", "phsubd", "phsubsw", "phsubw", "pinsrb", "pinsrd", "pinsrq", "pinsrw", "pmaddubsw", "pmaddwd",
        "pmaxsb", "pmaxsd", "pmaxsq", "pmaxsw", "pmaxub", "pmaxud", "pmaxuq", "pmaxuw", "pminsb", "pminsd", "pminsq",
        "pminsw", "pminub", "pminud", "pminuq", "pminuw", "pmovmskb", "pmovsx", "pmovzx", "pmuldq", "pmulhrsw",
        "pmulhuw", "pmulhw", "pmulld", "pmullw", "pmuludq", "por", "psadbw", "pshufb", "pshufd", "pshufhw", "pshuflw",
        "psignb", "psignd", "psignw", "pslld", "pslldq", "psllq", "psllw", "psraw", "psrld", "psrldq", "psrlq", "psrlw",
        "psubb", "psubd", "psubq", "psubsb", "psubsw", "psubusb", "psubusw", "psubw", "ptest", "punpckhbw", "punpckhdq",
        "punpckhqdq", "punpckhwd", "punpcklbw", "punpckldq", "punpcklqdq", "punpcklwd", "pxor", "pxord", "pxorq",
        "rcpps", "rcpss", "roundpd", "roundps", "roundsd", "roundss", "rsqrtps", "rsqrtss", "shufpd", "shufps",
        "sqrtpd", "sqrtps", "sqrtsd", "sqrtss", "stmxcsr", "subpd", "subps", "subsd", "subss", "ucomisd", "ucomiss",
        "unpckhpd", "unpckhps", "unpcklpd", "unpcklps", "vbroadcast", "vextractf128", "vextractf32x4", "vextractf64x4",
        "vinsertf128", "vinsertf32x4", "vinsertf64x4", "vmaskmov", "vmovdqu32", "vmovdqu64", "vperm2f128", "vpermilpd",
        "vpermilps", "vtestpdvtestps", "vzeroall", "vzeroupper", "xorpd", "xorps"}
    ORACLE_INTEL_AMD__AVX2 = {
        "movntdqa", "mpsadbw", "pabsb", "pabsd", "pabsq", "pabsw", "packssdw", "packsswb", "packusdw", "packuswb",
        "paddb", "paddd", "paddq", "paddsb", "paddsw", "paddusb", "paddusw", "paddw", "palignr", "pand", "pandn",
        "pavgb", "pavgw", "pblendvb", "pblendw", "pcmpeqb", "pcmpeqd", "pcmpeqq", "pcmpeqw", "pcmpgtb", "pcmpgtd",
        "pcmpgtq", "pcmpgtw", "phaddd", "phaddsw", "phaddw", "phsubd", "phsubsw", "phsubw", "pmaddubsw", "pmaddwd",
        "pmaxsb", "pmaxsd", "pmaxsq", "pmaxsw", "pmaxub", "pmaxud", "pmaxuq", "pmaxuw", "pminsb", "pminsd", "pminsq",
        "pminsw", "pminub", "pminud", "pminuq", "pminuw", "pmovmskb", "pmovsx", "pmovzx", "pmuldq", "pmulhrsw",
        "pmulhuw", "pmulhw", "pmulld", "pmullw", "pmuludq", "por", "psadbw", "pshufb", "pshufd", "pshufhw", "pshuflw",
        "psignb", "psignd", "psignw", "pslld", "pslldq", "psllq", "psllw", "psrad", "psraq", "psraw", "psrld", "psrldq",
        "psrlq", "psrlw", "psubb", "psubd", "psubq", "psubsb", "psubsw", "psubusb", "psubusw", "psubw", "punpckhbw",
        "punpckhdq", "punpckhqdq", "punpckhwd", "punpcklbw", "punpckldq", "punpcklqdq", "punpcklwd", "pxor", "pxord",
        "pxorq", "vbroadcast", "vbroadcasti128", "vextracti128", "vextracti32x4", "vextracti64x4", "vgatherdpd",
        "vgatherdps", "vgatherqpd", "vgatherqps", "vinserti128", "vinserti32x4", "vinserti64x4", "vpblendd",
        "vpbroadcast", "vperm2i128", "vpermd", "vpermpd", "vpermps", "vpermq", "vpgatherdd", "vpgatherdq", "vpgatherqd",
        "vpgatherqq", "vpmaskmov", "vpsllvd", "vpsllvq", "vpsllvw", "vpsravd", "vpsravq", "vpsrlvd", "vpsrlvq",
        "vpsrlvw"}
    ORACLE_SOLARIS__AVX = {
        "vaddpd", "vaddps", "vaddsd", "vaddss", "vaddsubpd", "vaddsubps", "vandnpd", "vandnps", "vandpd", "vandps",
        "vblendpd", "vblendps", "vblendvpd", "vblendvps", "vbroadcast", "vbroadcastf128", "vbroadcastsd",
        "vbroadcastss", "vcmpeq_ospd", "vcmpeq_osps", "vcmpeq_ossd", "vcmpeq_osss", "vcmpeq_uqpd", "vcmpeq_uqps",
        "vcmpeq_uqsd", "vcmpeq_uqss", "vcmpeq_uspd", "vcmpeq_usps", "vcmpeq_ussd", "vcmpeq_usss", "vcmpeqpd",
        "vcmpeqps", "vcmpeqsd", "vcmpeqss", "vcmpfalse_ospd", "vcmpfalse_osps", "vcmpfalse_ossd", "vcmpfalse_osss",
        "vcmpfalsepd", "vcmpfalseps", "vcmpfalsesd", "vcmpfalsess", "vcmpge_oqpd", "vcmpge_oqps", "vcmpge_oqsd",
        "vcmpge_oqss", "vcmpgepd", "vcmpgeps", "vcmpgesd", "vcmpgess", "vcmpgt_oqpd", "vcmpgt_oqps", "vcmpgt_oqsd",
        "vcmpgt_oqss", "vcmpgtpd", "vcmpgtps", "vcmpgtsd", "vcmpgtss", "vcmple_oqpd", "vcmple_oqps", "vcmple_oqsd",
        "vcmple_oqss", "vcmplepd", "vcmpleps", "vcmplesd", "vcmpless", "vcmplt_oqpd", "vcmplt_oqps", "vcmplt_oqsd",
        "vcmplt_oqss", "vcmpltpd", "vcmpltps", "vcmpltsd", "vcmpltss", "vcmpneq_oqpd", "vcmpneq_oqps", "vcmpneq_oqsd",
        "vcmpneq_oqss", "vcmpneq_ospd", "vcmpneq_osps", "vcmpneq_ossd", "vcmpneq_osss", "vcmpneq_uspd", "vcmpneq_usps",
        "vcmpneq_ussd", "vcmpneq_usss", "vcmpneqpd", "vcmpneqps", "vcmpneqsd", "vcmpneqss", "vcmpnge_uqpd",
        "vcmpnge_uqps", "vcmpnge_uqsd", "vcmpnge_uqss", "vcmpngepd", "vcmpngeps", "vcmpngesd", "vcmpngess",
        "vcmpngt_uqpd", "vcmpngt_uqps", "vcmpngt_uqsd", "vcmpngt_uqss", "vcmpngtpd", "vcmpngtps", "vcmpngtsd",
        "vcmpngtss", "vcmpnle_uqpd", "vcmpnle_uqps", "vcmpnle_uqsd", "vcmpnle_uqss", "vcmpnlepd", "vcmpnleps",
        "vcmpnlesd", "vcmpnless", "vcmpnlt_uqpd", "vcmpnlt_uqps", "vcmpnlt_uqsd", "vcmpnlt_uqss", "vcmpnltpd",
        "vcmpnltps", "vcmpnltsd", "vcmpnltss", "vcmpord_spd", "vcmpord_sps", "vcmpord_ssd", "vcmpord_sss", "vcmpordpd",
        "vcmpordps", "vcmpordsd", "vcmpordss", "vcmppd", "vcmpps", "vcmpsd", "vcmpss", "vcmptrue_uspd", "vcmptrue_usps",
        "vcmptrue_ussd", "vcmptrue_usss", "vcmptruepd", "vcmptrueps", "vcmptruesd", "vcmptruess", "vcmpunord_spd",
        "vcmpunord_sps", "vcmpunord_ssd", "vcmpunord_sss", "vcmpunordpd", "vcmpunordps", "vcmpunordsd", "vcmpunordss",
        "vcomisd", "vcomiss", "vcvtdq2pd", "vcvtdq2ps", "vcvtpd2dq", "vcvtpd2dqx", "vcvtpd2dqy", "vcvtpd2ps",
        "vcvtpd2psx", "vcvtpd2psy", "vcvtps2dq", "vcvtps2pd", "vcvtsd2si", "vcvtsd2sil", "vcvtsd2siq", "vcvtsd2ss",
        "vcvtsi2sd", "vcvtsi2sdl", "vcvtsi2sdq", "vcvtsi2ss", "vcvtsi2ssl", "vcvtsi2ssq", "vcvtss2sd", "vcvtss2si",
        "vcvtss2sil", "vcvtss2siq", "vcvttpd2dq", "vcvttpd2dqx", "vcvttpd2dqy", "vcvttps2dq", "vcvttsd2si",
        "vcvttsd2sil", "vcvttsd2siq", "vcvttss2si", "vcvttss2sil", "vcvttss2siq", "vdivpd", "vdivps", "vdivsd",
        "vdivss", "vdppd", "vdpps", "vextractf128", "vextractps", "vhaddpd", "vhaddps", "vhsubpd", "vhsubps",
        "vinsertf128", "vinsertps", "vlddqu", "vldmxcsr", "vmaskmov", "vmaskmovdqu", "vmaskmovpd", "vmaskmovps",
        "vmaxpd", "vmaxps", "vmaxsd", "vmaxss", "vminpd", "vminps", "vminsd", "vminss", "vmov", "vmovapd", "vmovaps",
        "vmovd", "vmovddup", "vmovdqa", "vmovdqu", "vmovhlps", "vmovhpd", "vmovhps", "vmovlhps", "vmovlpd", "vmovlps",
        "vmovmskpd", "vmovmskps", "vmovntdq", "vmovntdqa", "vmovntpd", "vmovntps", "vmovq", "vmovsd", "vmovshdup",
        "vmovsldup", "vmovss", "vmovupd", "vmovups", "vmpsadbw", "vmulpd", "vmulps", "vmulsd", "vmulss", "vorpd",
        "vorps", "vpabs", "vpabsb", "vpabsd", "vpabsq", "vpabsw", "vpackss", "vpackssdw", "vpacksswb", "vpackusdw",
        "vpackuswb", "vpadd", "vpaddb", "vpaddd", "vpaddq", "vpadds", "vpaddsb", "vpaddsw", "vpaddus", "vpaddusb",
        "vpaddusw", "vpaddw", "vpalignr", "vpand", "vpandn", "vpavg", "vpavgb", "vpavgw", "vpblendvb", "vpblendw",
        "vpclmulqdq", "vpcmpeq", "vpcmpeqb", "vpcmpeqd", "vpcmpeqq", "vpcmpeqw", "vpcmpestri", "vpcmpestrm", "vpcmpgt",
        "vpcmpgtb", "vpcmpgtd", "vpcmpgtq", "vpcmpgtw", "vpcmpistri", "vpcmpistrm", "vperm2f128", "vpermilpd",
        "vpermilps", "vpextr", "vpextrb", "vpextrd", "vpextrq", "vpextrw", "vphadd", "vphaddd", "vphaddsw", "vphaddw",
        "vphminposuw", "vphsub", "vphsubd", "vphsubsw", "vphsubw", "vpinsr", "vpinsrb", "vpinsrd", "vpinsrq", "vpinsrw",
        "vpmaddubsw", "vpmaddwd", "vpmaxs", "vpmaxsb", "vpmaxsd", "vpmaxsw", "vpmaxub", "vpmaxud", "vpmaxuw", "vpminsb",
        "vpminsd", "vpminsw", "vpminub", "vpminud", "vpminuw", "vpmovmskb", "vpmovsx", "vpmovsxbd", "vpmovsxbq",
        "vpmovsxbw", "vpmovsxdq", "vpmovsxwd", "vpmovsxwq", "vpmovzx", "vpmovzxbd", "vpmovzxbq", "vpmovzxbw",
        "vpmovzxdq", "vpmovzxwd", "vpmovzxwq", "vpmuldq", "vpmulhrsw", "vpmulhuw", "vpmulhw", "vpmulld", "vpmullw",
        "vpmuludq", "vpor", "vpsadbw", "vpshufb", "vpshufd", "vpshufhw", "vpshuflw", "vpsign", "vpsignb", "vpsignd",
        "vpsignw", "vpsll", "vpslld", "vpslldq", "vpsllq", "vpsllw", "vpsra", "vpsrad", "vpsraw", "vpsrl", "vpsrld",
        "vpsrldq", "vpsrlq", "vpsrlw", "vpsub", "vpsubb", "vpsubd", "vpsubq", "vpsubs", "vpsubsb", "vpsubsw", "vpsubus",
        "vpsubusb", "vpsubusw", "vpsubw", "vptest", "vpunpckh", "vpunpckhbw", "vpunpckhdq", "vpunpckhqdq", "vpunpckhwd",
        "vpunpckl", "vpunpcklbw", "vpunpckldq", "vpunpcklqdq", "vpunpcklwd", "vpxor", "vrcpps", "vrcpss", "vroundpd",
        "vroundps", "vroundsd", "vroundss", "vrsqrtps", "vrsqrtss", "vshufpd", "vshufps", "vsqrtpd", "vsqrtps",
        "vsqrtsd", "vsqrtss", "vstmxcsr", "vsubpd", "vsubps", "vsubsd", "vsubss", "vtestp", "vtestpd", "vtestps",
        "vucomisd", "vucomiss", "vunpckhpd", "vunpckhps", "vunpcklpd", "vunpcklps", "vxorpd", "vxorps", "vzeroall",
        "vzeroupper"}
    ORACLE_SOLARIS__AVX2 = {
        "vbroadcast", "vbroadcasti128", "vbroadcastsd", "vbroadcastss", "vextracti128", "vgatherdp", "vgatherdpd",
        "vgatherdps", "vgatherqp", "vgatherqpd", "vgatherqps", "vinserti128", "vmovntdqa", "vmpsadbw", "vpabs",
        "vpabsb", "vpabsd", "vpabsw", "vpackss", "vpackssdw", "vpacksswb", "vpackusdw", "vpackuswb", "vpadd", "vpaddb",
        "vpaddd", "vpaddq", "vpadds", "vpaddsb", "vpaddsw", "vpaddus", "vpaddusb", "vpaddusw", "vpaddw", "vpalignr",
        "vpand", "vpandn", "vpavg", "vpavgb", "vpavgw", "vpblendd", "vpblendvb", "vpblendw", "vpbroadcast",
        "vpbroadcastb", "vpbroadcastd", "vpbroadcastq", "vpbroadcastw", "vpcmpeq", "vpcmpeqb", "vpcmpeqd", "vpcmpeqq",
        "vpcmpeqw", "vpcmpgt", "vpcmpgtb", "vpcmpgtd", "vpcmpgtq", "vpcmpgtw", "vperm2i128", "vpermd", "vpermpd",
        "vpermps", "vpermq", "vpgatherdd", "vpgatherdq", "vpgatherqd", "vpgatherqq", "vphadd", "vphaddd", "vphaddsw",
        "vphaddw", "vphsub", "vphsubd", "vphsubsw", "vphsubw", "vpmaddubsw", "vpmaddwd", "vpmaskmov", "vpmaskmovd",
        "vpmaskmovq", "vpmaxs", "vpmaxsb", "vpmaxsd", "vpmaxsw", "vpmaxub", "vpmaxud", "vpmaxuw", "vpminsb", "vpminsd",
        "vpminsw", "vpminub", "vpminud", "vpminuw", "vpmovmskb", "vpmovsx", "vpmovsxbd", "vpmovsxbq", "vpmovsxbw",
        "vpmovsxdq", "vpmovsxwd", "vpmovsxwq", "vpmovzx", "vpmovzxbd", "vpmovzxbq", "vpmovzxbw", "vpmovzxdq",
        "vpmovzxwd", "vpmovzxwq", "vpmuldq", "vpmulhrsw", "vpmulhuw", "vpmulhw", "vpmulld", "vpmullw", "vpmuludq",
        "vpor", "vpsadbw", "vpshufb", "vpshufd", "vpshufhw", "vpshuflw", "vpsign", "vpsignb", "vpsignd", "vpsignw",
        "vpsll", "vpslld", "vpslldq", "vpsllq", "vpsllv", "vpsllvd", "vpsllvq", "vpsllw", "vpsra", "vpsrad", "vpsravd",
        "vpsraw", "vpsrl", "vpsrld", "vpsrldq", "vpsrlq", "vpsrlv", "vpsrlvd", "vpsrlvq", "vpsrlw", "vpsub", "vpsubb",
        "vpsubd", "vpsubq", "vpsubs", "vpsubsb", "vpsubsw", "vpsubus", "vpsubusb", "vpsubusw", "vpsubw", "vpunpckh",
        "vpunpckhbw", "vpunpckhdq", "vpunpckhqdq", "vpunpckhwd", "vpunpckl", "vpunpcklbw", "vpunpckldq", "vpunpcklqdq",
        "vpunpcklwd", "vpxor"}
    ORACLE_INTEL_AMD__BMI1 = {"andn", "bextr", "blsi", "blsmsk", "blsr", "lzcnt", "tzcnt"}
    ORACLE_INTEL_AMD__BMI2 = {"bzhi", "mulx", "pdep", "pext", "rorx", "sarx", "shlx", "shrx"}
    ORACLE_INTEL_AMD__F16C = {"vcvtph2ps", "vcvtps2ph"}
    ORACLE_INTEL_AMD__FMA = {"vfmadd132pd", "vfmadd132ps", "vfmadd132sd", "vfmadd132ss", "vfmadd213pd", "vfmadd213ps",
                             "vfmadd213sd", "vfmadd213ss", "vfmadd231pd", "vfmadd231ps", "vfmadd231sd", "vfmadd231ss",
                             "vfmaddsub132pd", "vfmaddsub132ps", "vfmaddsub213pd", "vfmaddsub213ps", "vfmaddsub231pd",
                             "vfmaddsub231ps", "vfmsub132pd", "vfmsub132ps", "vfmsub132sd", "vfmsub132ss",
                             "vfmsub213pd", "vfmsub213ps", "vfmsub213sd", "vfmsub213ss", "vfmsub231pd", "vfmsub231ps",
                             "vfmsub231sd", "vfmsub231ss", "vfmsubadd132pd", "vfmsubadd132ps", "vfmsubadd213pd",
                             "vfmsubadd213ps", "vfmsubadd231pd", "vfmsubadd231ps", "vfnmadd132pd", "vfnmadd132ps",
                             "vfnmadd132sd", "vfnmadd132ss", "vfnmadd213pd", "vfnmadd213ps", "vfnmadd213sd",
                             "vfnmadd213ss", "vfnmadd231pd", "vfnmadd231ps", "vfnmadd231sd", "vfnmadd231ss",
                             "vfnmsub132pd", "vfnmsub132ps", "vfnmsub132sd", "vfnmsub132ss", "vfnmsub213pd",
                             "vfnmsub213ps", "vfnmsub213sd", "vfnmsub213ss", "vfnmsub231pd", "vfnmsub231ps",
                             "vfnmsub231sd", "vfnmsub231ss"}
    ORACLE_INTEL_AMD__FSGSBASE = {"rdfsbase", "rdgsbase", "wrfsbase", "wrgsbase"}
    ORACLE_INTEL_AMD__MMX = {
        "emms", "movd", "movq", "packssdw", "packsswb", "packuswb", "paddb", "paddd", "paddsb", "paddsw", "paddusb",
        "paddusw", "paddw", "pand", "pandn", "pcmpeqb", "pcmpeqd", "pcmpeqw", "pcmpgtb", "pcmpgtd", "pcmpgtw",
        "pmaddwd", "pmulhw", "pmullw", "por", "pslld", "psllq", "psllw", "psrad", "psraw", "psrld", "psrlq", "psrlw",
        "psubb", "psubd", "psubsb", "psubsw", "psubusb", "psubusw", "psubw", "punpckhbw", "punpckhdq", "punpckhwd",
        "punpcklbw", "punpckldq", "punpcklwd", "pxor"}
    ORACLE_INTEL_AMD__MOVBE = {"movbe"}
    ORACLE_INTEL_AMD__PCLMULQDQ = {"pclmulqdq"}
    ORACLE_INTEL_AMD__PREFETCH = {"prefetch", "prefetchw", "prefetchwt1"}
    ORACLE_INTEL_AMD__RDRAND = {"rdrand"}
    ORACLE_INTEL_AMD__RDSEED = {"rdseed"}
    ORACLE_INTEL_AMD__SSE = {
        "addps", "addss", "andnps", "andps", "cmpps", "cmpss", "comiss", "cvtpi2ps", "cvtps2pi", "cvtsi2ss", "cvtss2si",
        "cvttps2pi", "cvttss2si", "divps", "divss", "ldmxcsr", "maskmovq", "maxps", "maxss", "minps", "minss", "movaps",
        "movhlps", "movhps", "movlhps", "movlps", "movmskps", "movntps", "movntq", "movss", "movups", "mulps", "mulss",
        "orps", "pavgb", "pavgw", "pextrw", "pinsrw", "pmaxsw", "pmaxub", "pminsw", "pminub", "pmovmskb", "pmulhuw",
        "prefetchnta", "prefetcht0", "prefetcht1", "prefetcht2", "psadbw", "pshufw", "rcpps", "rcpss", "rsqrtps",
        "rsqrtss", "sfence", "shufps", "sqrtps", "sqrtss", "stmxcsr", "subps", "subss", "ucomiss", "unpckhps",
        "unpcklps", "xorps"}
    ORACLE_INTEL_AMD__SSE2 = {
        "addpd", "addsd", "andnpd", "andpd", "clflush", "cmppd", "cmpsd", "comisd", "cvtdq2pd", "cvtdq2ps", "cvtpd2dq",
        "cvtpd2pi", "cvtpd2ps", "cvtpi2pd", "cvtps2dq", "cvtps2pd", "cvtsd2si", "cvtsd2ss", "cvtsi2sd", "cvtss2sd",
        "cvttpd2dq", "cvttpd2pi", "cvttps2dq", "cvttsd2si", "divpd", "divsd", "lfence", "maskmovdqu", "maxpd", "maxsd",
        "mfence", "minpd", "minsd", "movapd", "movdq2q", "movdqa", "movdqu", "movhpd", "movlpd", "movmskpd", "movntdq",
        "movnti", "movntpd", "movq2dq", "movsd", "movupd", "mulpd", "mulsd", "orpd", "paddq", "pause", "pmuludq",
        "pshufd", "pshufhw", "pshuflw", "pslldq", "psrldq", "psubq", "punpckhqdq", "punpcklqdq", "shufpd", "sqrtpd",
        "sqrtsd", "subpd", "subsd", "ucomisd", "unpckhpd", "unpcklpd", "xorpd"}
    ORACLE_INTEL_AMD__SSE3 = {
        "addsubpd", "addsubps", "haddpd", "haddps", "hsubpd", "hsubps", "lddqu", "movddup", "movshdup", "movsldup"}
    ORACLE_INTEL_AMD__SSE4a = {"extrq", "insertq", "movntsd", "movntss"}
    ORACLE_INTEL_AMD__SSE41 = {
        "blendpd", "blendps", "blendvpd", "blendvps", "dppd", "dpps", "extractps", "insertps", "movntdqa", "mpsadbw",
        "packusdw", "pblendvb", "pblendw", "pcmpeqb", "pcmpeqd", "pcmpeqq", "pcmpeqw", "pextrb", "pextrd", "pextrq",
        "pextrw", "phminposuw", "pinsrb", "pinsrd", "pinsrq", "pmaxsb", "pmaxsd", "pmaxsq", "pmaxsw", "pmaxud",
        "pmaxuq", "pmaxuw", "pminsb", "pminsd", "pminsq", "pminud", "pminuq", "pminuw", "pmovsx", "pmovzx", "pmuldq",
        "pmulld", "ptest", "roundpd", "roundps", "roundsd", "roundss"}
    ORACLE_INTEL_AMD__SSE42 = {"pcmpestri", "pcmpestrm", "pcmpgtq", "pcmpistri", "pcmpistrm"}
    ORACLE_INTEL_AMD__SSSE3 = {
        "pabsb", "pabsd", "pabsq", "pabsw", "palignr", "phaddd", "phaddsw", "phaddw", "phsubd", "phsubsw", "phsubw",
        "pmaddubsw", "pmulhrsw", "pshufb", "psignb", "psignd", "psignw"}
    ORACLE_SOLARIS__SSE41 = {
        "pmovsx", "pmovsxbd", "pmovsxbq", "pmovsxbw", "pmovsxdq", "pmovsxwd", "pmovsxwq", "pmovzx", "pmovzxbd",
        "pmovzxbq", "pmovzxbw", "pmovzxdq", "pmovzxwd", "pmovzxwq"}
    ORACLE_INTEL_AMD__TRANS_SYCN_EXT = {
        "xabort", "xbegin", "xbeginl", "xbeginw", "xend", "xtest"}
    ORACLE_INTEL_AMD__OP_SYS_SUPPORT = {
        "arpl", "clts", "hlt", "invd", "invlpg", "lar", "lgdt", "lidt", "lldt", "lmsw", "lock", "lsl", "ltr", "rdmsr",
        "rdpmc", "rdtsc", "rsm", "sgdt", "sidt", "sldt", "smsw", "str", "sysenter", "sysexit", "verr", "verw", "wbinvd",
        "wrmsr"}
    ORACLE_INTEL_AMD__VMX = {
        "invept", "invvpid", "vmcall", "vmclear", "vmfunc", "vmlaunch", "vmptrld", "vmptrst", "vmread", "vmresume",
        "vmwrite", "vmxoff", "vmxon"}
    ORACLE_INTEL_AMD__XSAVE = {"xsaveopt", "xsaveopt64"}
    ORACLE_INTEL_AMD__3DNOW = {
        "femms", "pavgusb", "pf2id", "pf2iw", "pfacc", "pfadd", "pfcmpeq", "pfcmpge", "pfcmpgt", "pfmax", "pfmin",
        "pfmul", "pfnacc", "pfpnacc", "pfrcp", "pfrcpit1", "pfrcpit2", "pfrsqit1", "pfrsqrt", "pfsub", "pfsubr",
        "pi2fd", "pi2fw", "pmulhrw", "pswapd"}

    NEW_AVX = {'vcmpngt_uqsd', 'vcmpgt_oqpd', 'vcmpeq_ossd', 'vcmpeq_uqps', 'vcmpnle_uqps', 'vcmpeq_uqss', 'pmvnzb',
               'vcmpneq_oqss', 'vcmpnle_uspd', 'vfmaddsub312pd', 'vfmsub321ss', 'vcmpnlt_uspd', 'vcmpfalse_osps',
               'vcmpunord_qss', 'vcmpneq_ussd', 'vfnmadd321sd', 'vcmple_ossd', 'vcmpunordss', 'vcmpeq_uqpd', 'rsts',
               'vcmpngt_usss', 'vfmsub321ps', 'vcmpnlt_ussd', 'vcmpneq_osss', 'vfmsubadd312ps', 'vcmpunord_sps',
               'vcmpnge_uqps', 'vcmpngt_uqpd', 'vcmpneqss', 'rsldt', 'vcmple_oqss', 'vcmple_oqps', 'vfmaddsub123ps',
               'vcmpneq_osps', 'vfmsub123ss', 'vcmpngt_uqss', 'pclmullqlqdq', 'vcmpgt_oqss', 'vfmadd312sd',
               'vcmpneq_uqss', 'pclmullqhqdq', 'vfnmsub321pd', 'vcmpnge_uqss', 'vcmpunord_qps', 'vfmaddsub321ps',
               'vcmplt_oqss', 'vcmpeq_ospd', 'vcmptrue_uspd', 'rsdc', 'vcmpnleps', 'wrshr', 'vcmpord_sps', 'vcmpngtss',
               'vcmpneq_usps', 'vcmple_osps', 'vcmpngtpd', 'vfmaddsub312ps', 'vcmple_ospd', 'vcmpnlt_uqpd',
               'vcmpord_qpd', 'vcmpfalse_oqpd', 'vcmpnge_uspd', 'vfmsub312ss', 'vcmpltpd', 'pmvlzb', 'vcmpnle_ussd',
               'pmvzb', 'vcmpordps', 'vfmsub312pd', 'pmulhriw', 'vcmpngt_usps', 'vcmpge_oqss', 'vcmpge_oqsd',
               'vcmpltsd', 'paveb', 'vfnmadd312ss', 'pmachriw', 'vcmplt_osps', 'vfnmadd312sd', 'vcmpordsd', 'pdistib',
               'vfmsubadd321pd', 'vfmaddsub321pd', 'svts', 'vfmadd123ss', 'vcmpnlesd', 'vcmpunord_qpd', 'pmagw',
               'vcmpunord_sss', 'vfnmadd321pd', 'vcmplt_ossd', 'vcmpltps', 'vcmpfalse_oqss', 'vcmpgtsd', 'vcmplepd',
               'vcmpge_oqps', 'vcmpfalsesd', 'vcmpngt_uqps', 'vcmpneq_oqps', 'vcmptruepd', 'svdc', 'vcmple_osss',
               'vcmpnle_uqpd', 'vcmpunordps', 'vcmpfalsess', 'vfmadd123sd', 'vfnmadd123sd', 'vcmptrue_ussd', 'svldt',
               'cpu_read', 'smint', 'vcmpgess', 'vcmpgt_ospd', 'vfmadd312pd', 'vcmpgt_osps', 'vfmsubadd312pd',
               'vcmpgesd', 'vcmpgt_ossd', 'vcmpord_qps', 'pfrsqrtv', 'vfnmsub312sd', 'vcmpgeps', 'vcmpordpd', 'paddsiw',
               'vcmpngtps', 'vcmpfalse_ospd', 'vcmpneqsd', 'pclmulhqhqdq', 'ud2a', 'vfnmadd321ss', 'vfmadd123pd',
               'vfnmadd312ps', 'vcmplt_oqps', 'vcmpgtpd', 'vfnmsub321sd', 'vcmpnlt_uqps', 'vcmpunord_qsd', 'vcmplesd',
               'vcmpneq_oqpd', 'vfnmadd123pd', 'vcmpltss', 'vfmadd321ss', 'vcmplt_oqsd', 'vcmpnle_usss', 'vcmpge_ospd',
               'vcmpfalseps', 'vcmpordss', 'vfnmsub312ps', 'vcmpnle_usps', 'vfmsub321pd', 'vcmpneq_ospd',
               'vfnmadd312pd', 'vcmpge_osps', 'vcmpneq_ossd', 'vpclmulhqhqdq', 'vcmpneqps', 'vfmsub312ps', 'vcmpneqpd',
               'vfnmsub321ss', 'vcmpge_ossd', 'vcmpngeps', 'vcmplt_osss', 'vpclmullqhqdq', 'vcmpnge_uqsd', 'vcmpgtps',
               'vfmadd312ss', 'vcmpneq_usss', 'vcmple_oqpd', 'vcmpngesd', 'vcmpnltsd', 'vcmptrue_uqpd', 'vfnmsub123ps',
               'vcmple_oqsd', 'vcmpeq_uspd', 'vcmpnltss', 'vcmpge_osss', 'cpu_write', 'vcmpnge_usss', 'vcmpnge_uqpd',
               'rdm', 'vcmpless', 'pmvgezb', 'vcmplt_ospd', 'vfnmadd123ss', 'vcmpngt_ussd', 'vcmptrue_uqss', 'int03',
               'vcmpgepd', 'pfrcpv', 'vcmpnltps', 'rdshr', 'vfnmsub312ss', 'vfmadd123ps', 'vfnmadd123ps', 'psubsiw',
               'vcmpeqps', 'vcmpnle_uqsd', 'vcmpeq_usps', 'vcmpnlt_uqss', 'vldqqu', 'vcmpnless', 'vfmadd321sd',
               'vcmpngt_uspd', 'vcmpeq_ussd', 'vcmptrueps', 'vcmpord_sss', 'vcmpnlepd', 'int01', 'vcmpeqss', 'iretw',
               'vcmpunord_ssd', 'vfmsub321sd', 'vcmpnlt_usps', 'vcmpneq_uqsd', 'vcmptrue_usss', 'vfnmsub321ps',
               'vcmpnle_uqss', 'vpclmullqlqdq', 'vfmsubadd123ps', 'vfnmsub312pd', 'vfmsubadd123pd', 'vcmpnlt_usss',
               'dmint', 'vfmadd321ps', 'vcmpgt_osss', 'vfmsub123sd', 'vcmpeq_osss', 'vcmpneq_uqps', 'vcmpngepd',
               'vcmpunordsd', 'vcmpfalsepd', 'vmovqqa', 'vcmpfalse_oqps', 'vcmpgt_oqps', 'vcmpord_qsd', 'vcmptruess',
               'vfmsubadd321ps', 'vcmplt_oqpd', 'vfmadd321pd', 'vcmpgtss', 'pclmulhqlqdq', 'vcmpfalse_osss',
               'vcmpunord_spd', 'vcmptrue_uqps', 'vfmadd312ps', 'vcmpnge_usps', 'vcmpgt_oqsd', 'vcmpeqpd',
               'vcmpunordpd', 'vfnmadd321ps', 'vcmpneq_uspd', 'vcmpord_spd', 'vcmpngess', 'pmulhrwa', 'vmovqqu',
               'vcmptrue_uqsd', 'vcmpord_qss', 'vcmpfalse_ossd', 'vcmpge_oqpd', 'vcmpleps', 'vfmsub312sd',
               'vcmpeq_usss', 'vpclmulhqlqdq', 'vfnmsub123pd', 'vfmsub123ps', 'vcmptrue_usps', 'vcmpneq_oqsd',
               'vcmpeq_uqsd', 'vcmpngtsd', 'vcmpnltpd', 'vcmpfalse_oqsd', 'vcmpord_ssd', 'vfmaddsub123pd', 'vmovntqq',
               'vcmpnlt_uqsd', 'vcmpeqsd', 'vfnmsub123sd', 'pmulhrwc', 'vfnmsub123ss', 'vcmpneq_uqpd', 'vcmpeq_osps',
               'vcmptruesd', 'vfmsub123pd', 'vcmpnge_ussd'}
