from enum import Enum


class Mnemonics(Enum):
    """
    libr/asm/d/x86.c: static const struct kv kvs[]
    """
    _ALL = {
        "aaa", "aad", "aam", "aas", "adc", "adcx", "add", "addpd", "addps", "addsd", "addss", "addsubpd", "addsubps",
        "adox", "aesdec", "aesdeclast", "aesenc", "aesenclast", "aesimc", "aeskeygenassist", "and", "andn", "andnpd",
        "andnps", "andpd", "andps", "arpl", "bextr", "blendpd", "blendps", "blendvpd", "blendvps", "blsi", "blsmsk",
        "blsr", "bndcl", "bndcn", "bndcu", "bndldx", "bndmk", "bndmov", "bndstx", "bound", "bsf", "bsr", "bswap", "bt",
        "btc", "btr", "bts", "bzhi", "call", "callf", "cbw", "cdq", "cdqe", "clac", "clc", "cld", "clflush",
        "clflushopt", "cli", "clts", "cmc", "cmova", "cmovae", "cmovb", "cmovbe", "cmovc", "cmove", "cmovg", "cmovge",
        "cmovl", "cmovle", "cmovna", "cmovnae", "cmovnb", "cmovnbe", "cmovnc", "cmovne", "cmovng", "cmovnge", "cmovnl",
        "cmovnle", "cmovno", "cmovnp", "cmovns", "cmovnz", "cmovo", "cmovp", "cmovpe", "cmovpo", "cmovs", "cmovz",
        "cmp", "cmppd", "cmpps", "cmps", "cmpsb", "cmpsd", "cmpsq", "cmpss", "cmpsw", "cmpxchg", "cmpxchg16b",
        "cmpxchg8b", "comisd", "comiss", "cpuid", "cqo", "crc32", "cs", "cvtdq2pd", "cvtdq2ps", "cvtpd2dq", "cvtpd2pi",
        "cvtpd2ps", "cvtpi2pd", "cvtpi2ps", "cvtps2dq", "cvtps2pd", "cvtps2pi", "cvtsd2si", "cvtsd2ss", "cvtsi2sd",
        "cvtsi2ss", "cvtss2sd", "cvtss2si", "cvttpd2dq", "cvttpd2pi", "cvttps2dq", "cvttps2pi", "cvttsd2si",
        "cvttss2si", "cwd", "cwde", "daa", "das", "dec", "div", "divpd", "divps", "divsd", "divss", "dppd", "dpps",
        "ds", "emms", "enter", "es", "extractps", "f2xm1", "fabs", "fadd", "faddp", "fbld", "fbstp", "fchs", "fclex",
        "fcmovb", "fcmovbe", "fcmove", "fcmovnb", "fcmovnbe", "fcmovne", "fcmovnu", "fcmovu", "fcom", "fcomi", "fcomip",
        "fcomp", "fcompp", "fcos", "fdecstp", "fdisi", "fdiv", "fdivp", "fdivr", "fdivrp", "feni", "ffree", "ffreep",
        "fiadd", "ficom", "ficomp", "fidiv", "fidivr", "fild", "fimul", "fincstp", "finit", "fist", "fistp", "fisttp",
        "fisub", "fisubr", "fld", "fld1", "fldcw", "fldenv", "fldl2e", "fldl2t", "fldlg2", "fldln2", "fldpi", "fldz",
        "fmul", "fmulp", "fnclex", "fndisi", "fneni", "fninit", "fnop", "fnsave", "fnsetpm", "fnstcw", "fnstenv",
        "fnstsw", "fpatan", "fprem", "fprem1", "fptan", "frndint", "frstor", "fs", "fsave", "fscale", "fsetpm", "fsin",
        "fsincos", "fsqrt", "fst", "fstcw", "fstenv", "fstp", "fstpnce", "fstsw", "fsub", "fsubp", "fsubr", "fsubrp",
        "ftst", "fucom", "fucomi", "fucomip", "fucomp", "fucompp", "fwait", "fxam", "fxch", "fxrstor", "fxsave",
        "fxtract", "fyl2x", "fyl2xp1", "getsec", "gs", "haddpd", "haddps", "hint_nop", "hlt", "hsubpd", "hsubps",
        "icebp", "idiv", "imul", "in", "inc", "ins", "insb", "insd", "insertps", "insw", "int", "int1", "int3", "into",
        "invd", "invept", "invlpg", "invpcid", "invvpid", "iret", "iretd", "iretq", "ja", "jae", "jb", "jbe", "jc",
        "jcxz", "je", "jecxz", "jg", "jge", "jl", "jle", "jmp", "jmpe", "jmpf", "jna", "jnae", "jnb", "jnbe", "jnc",
        "jne", "jng", "jnge", "jnl", "jnle", "jno", "jnp", "jns", "jnz", "jo", "jp", "jpe", "jpo", "jrcxz", "js", "jz",
        "kaddb", "kaddd", "kaddq", "kaddw", "kandb", "kandd", "kandnb", "kandnd", "kandnq", "kandnw", "kandq", "kandw",
        "kmovb", "kmovd", "kmovq", "kmovw", "knotb", "knotd", "knotq", "knotw", "korb", "kord", "korq", "kortestb",
        "kortestd", "kortestq", "kortestw", "korw", "kshiftlb", "kshiftld", "kshiftlq", "kshiftlw", "kshiftrb",
        "kshiftrd", "kshiftrq", "kshiftrw", "ktestb", "ktestd", "ktestq", "ktestw", "kunpckbw", "kunpckdq", "kunpckwd",
        "kxnorb", "kxnord", "kxnorq", "kxnorw", "kxorb", "kxord", "kxorq", "kxorw", "lahf", "lar", "lddqu", "ldmxcsr",
        "lds", "lea", "leave", "les", "lfence", "lfs", "lgdt", "lgs", "lidt", "lldt", "lmsw", "loadall", "loadalld",
        "lock", "lods", "lodsb", "lodsd", "lodsq", "lodsw", "loop", "loope", "loopne", "loopnz", "loopz", "lsl", "lss",
        "ltr", "lzcnt", "maskmovdqu", "maskmovq", "maxpd", "maxps", "maxsd", "maxss", "mfence", "minpd", "minps",
        "minsd", "minss", "monitor", "mov", "movabs", "movapd", "movaps", "movbe", "movd", "movddup", "movdq2q",
        "movdqa", "movdqu", "movhlps", "movhpd", "movhps", "movlhps", "movlpd", "movlps", "movmskpd", "movmskps",
        "movntdq", "movntdqa", "movnti", "movntpd", "movntps", "movntq", "movq", "movq2dq", "movs", "movsb", "movsd",
        "movshdup", "movsldup", "movsq", "movss", "movsw", "movsx", "movsxd", "movupd", "movups", "movzx", "mpsadbw",
        "mul", "mulpd", "mulps", "mulsd", "mulss", "mulx", "mwait", "neg", "nop", "not", "or", "orpd", "orps", "out",
        "outs", "outsb", "outsd", "outsw", "pabsb", "pabsd", "pabsq", "pabsw", "packssdw", "packsswb", "packusdw",
        "packuswb", "paddb", "paddd", "paddq", "paddsb", "paddsw", "paddusb", "paddusw", "paddw", "palignr", "pand",
        "pandn", "pause", "pavgb", "pavgw", "pblendvb", "pblendw", "pclmulqdq", "pcmpeqb", "pcmpeqd", "pcmpeqq",
        "pcmpeqw", "pcmpestri", "pcmpestrm", "pcmpgtb", "pcmpgtd", "pcmpgtq", "pcmpgtw", "pcmpistri", "pcmpistrm",
        "pdep", "pext", "pextrb", "pextrd", "pextrq", "pextrw", "phaddd", "phaddsw", "phaddw", "phminposuw", "phsubd",
        "phsubsw", "phsubw", "pinsrb", "pinsrd", "pinsrq", "pinsrw", "pmaddubsw", "pmaddwd", "pmaxsb", "pmaxsd",
        "pmaxsq", "pmaxsw", "pmaxub", "pmaxud", "pmaxuq", "pmaxuw", "pminsb", "pminsd", "pminsq", "pminsw", "pminub",
        "pminud", "pminuq", "pminuw", "pmovmskb", "pmovsxbd", "pmovsxbq", "pmovsxbw", "pmovsxdq", "pmovsxwd",
        "pmovsxwq", "pmovzxbd", "pmovzxbq", "pmovzxbw", "pmovzxdq", "pmovzxwd", "pmovzxwq", "pmuldq", "pmulhrsw",
        "pmulhuw", "pmulhw", "pmulld", "pmullq", "pmullw", "pmuludq", "pop", "popa", "popad", "popal", "popcnt", "popf",
        "popfd", "popfl", "popfw", "popfq", "por", "prefetchnta", "prefetcht0", "prefetcht1", "prefetcht2", "prefetchw",
        "prefetchwt1", "prold", "prolq", "prolvd", "prolvq", "prord", "prorq", "prorvd", "prorvq", "psadbw", "pshufb",
        "pshufd", "pshufhw", "pshuflw", "pshufw", "psignb", "psignd", "psignw", "pslld", "pslldq", "psllq", "psllw",
        "psrad", "psraq", "psraw", "psrld", "psrldq", "psrlq", "psrlw", "psubb", "psubd", "psubq", "psubsb", "psubsw",
        "psubusb", "psubusw", "psubw", "ptest", "ptwrite", "punpckhbw", "punpckhdq", "punpckhqdq", "punpckhwd",
        "punpcklbw", "punpckldq", "punpcklqdq", "punpcklwd", "push", "pusha", "pushad", "pushal", "pushf", "pushfd",
        "pushfl", "pushfw", "pushfq", "pxor", "rcl", "rcpps", "rcpss", "rcr", "rdfsbase", "rdgsbase", "rdmsr", "rdpid",
        "rdpkru", "rdpmc", "rdrand", "rdseed", "rdtsc", "rdtscp", "ret", "retf", "retn", "rex", "rex.b", "rex.r",
        "rex.rb", "rex.rx", "rex.rxb", "rex.w", "rex.wb", "rex.wr", "rex.wrb", "rex.wrx", "rex.wrxb", "rex.wx",
        "rex.wxb", "rex.x", "rex.xb", "rol", "ror", "rorx", "roundpd", "roundps", "roundsd", "roundss", "rsm",
        "rsqrtps", "rsqrtss", "rtdsc", "sahf", "sal", "salc", "sar", "sarx", "sbb", "scas", "scasb", "scasd", "scasq",
        "scasw", "seta", "setae", "setb", "setbe", "setc", "sete", "setg", "setge", "setl", "setle", "setna", "setnae",
        "setnb", "setnbe", "setnc", "setne", "setng", "setnge", "setnl", "setnle", "setno", "setnp", "setns", "setnz",
        "seto", "setp", "setpe", "setpo", "sets", "setz", "sfence", "sgdt", "sha1msg1", "sha1msg2", "sha1nexte",
        "sha1rnds4", "sha256msg1", "sha256msg2", "sha256rnds2", "shl", "shld", "shlx", "shr", "shrd", "shrx", "shufpd",
        "shufps", "sidt", "sldt", "smsw", "sqrtpd", "sqrtps", "sqrtsd", "sqrtss", "ss", "stac", "stc", "std", "sti",
        "stmxcsr", "stos", "stosb", "stosd", "stosq", "stosw", "str", "sub", "subpd", "subps", "subsd", "subss",
        "swapgs", "syscall", "sysenter", "sysexit", "sysret", "test", "tzcnt", "ucomisd", "ucomiss", "ud1", "ud2",
        "unpckhpd", "unpckhps", "unpcklpd", "unpcklps", "vaddpd", "vaddps", "vaddsd", "vaddss", "vaddsubpd",
        "vaddsubps", "vaesdec", "vaesdeclast", "vaesenc", "vaesenclast", "vaesimc", "vaeskeygenassist", "valignd",
        "valignq", "vandnpd", "vandnps", "vandpd", "vandps", "vblendmpd", "vblendmps", "vblendpd", "vblendps",
        "vblendvpd", "vblendvps", "vbroadcastf128", "vbroadcastf32x2", "vbroadcastf32x4", "vbroadcastf32x8",
        "vbroadcastf64x2", "vbroadcastf64x4", "vbroadcasti32x2", "vbroadcasti32x8", "vbroadcasti64x4", "vbroadcastsd",
        "vbroadcastss", "vcmppd", "vcmpps", "vcmpsd", "vcmpss", "vcomisd", "vcomiss", "vcompresspd", "vcompressps",
        "vcvtdq2pd", "vcvtdq2ps", "vcvtpd2dq", "vcvtpd2ps", "vcvtpd2qq", "vcvtpd2udq", "vcvtpd2uqq", "vcvtph2ps",
        "vcvtps2dq", "vcvtps2pd", "vcvtps2ph", "vcvtps2qq", "vcvtps2udq", "vcvtps2uqq", "vcvtqq2pd", "vcvtqq2ps",
        "vcvtsd2si", "vcvtsd2ss", "vcvtsd2usi", "vcvtsi2sd", "vcvtsi2ss", "vcvtss2sd", "vcvtss2si", "vcvtss2usi",
        "vcvttpd2dq", "vcvttpd2qq", "vcvttpd2udq", "vcvttpd2uqq", "vcvttps2dq", "vcvttps2qq", "vcvttps2udq",
        "vcvttps2uqq", "vcvttsd2si", "vcvttsd2usi", "vcvttss2si", "vcvttss2usi", "vcvtudq2pd", "vcvtudq2ps",
        "vcvtuqq2pd", "vcvtuqq2ps", "vcvtusi2sd", "vcvtusi2ss", "vdbpsadbw", "vdivpd", "vdivps", "vdivsd", "vdivss",
        "vdppd", "vdpps", "verr", "verw", "vexp2pd", "vexp2ps", "vexpandpd", "vexpandps", "vextractf128",
        "vextractf32x4", "vextractf32x8", "vextractf64x2", "vextractf64x4", "vextracti128", "vextracti32x4",
        "vextracti32x8", "vextracti64x2", "vextracti64x4", "vextractps", "vfixupimmpd", "vfixupimmps", "vfixupimmsd",
        "vfixupimmss", "vfmadd132pd", "vfmadd132ps", "vfmadd132sd", "vfmadd132ss", "vfmadd213pd", "vfmadd213ps",
        "vfmadd213sd", "vfmadd213ss", "vfmadd231pd", "vfmadd231ps", "vfmadd231sd", "vfmadd231ss", "vfmaddsub132pd",
        "vfmaddsub132ps", "vfmaddsub213pd", "vfmaddsub213ps", "vfmaddsub231pd", "vfmaddsub231ps", "vfmsub132pd",
        "vfmsub132ps", "vfmsub132sd", "vfmsub132ss", "vfmsub213pd", "vfmsub213ps", "vfmsub213sd", "vfmsub213ss",
        "vfmsub231pd", "vfmsub231ps", "vfmsub231sd", "vfmsub231ss", "vfmsubadd132pd", "vfmsubadd132ps",
        "vfmsubadd213pd", "vfmsubadd213ps", "vfmsubadd231pd", "vfmsubadd231ps", "vfnmadd132pd", "vfnmadd132ps",
        "vfnmadd132sd", "vfnmadd132ss", "vfnmadd213pd", "vfnmadd213ps", "vfnmadd213sd", "vfnmadd213ss", "vfnmadd231pd",
        "vfnmadd231ps", "vfnmadd231sd", "vfnmadd231ss", "vfnmsub132pd", "vfnmsub132ps", "vfnmsub132sd", "vfnmsub132ss",
        "vfnmsub213pd", "vfnmsub213ps", "vfnmsub213sd", "vfnmsub213ss", "vfnmsub231pd", "vfnmsub231ps", "vfnmsub231sd",
        "vfnmsub231ss", "vfpclasspd", "vfpclassps", "vfpclasssd", "vfpclassss", "vgatherdpd", "vgatherdps",
        "vgatherpf0dpd", "vgatherpf0dps", "vgatherpf0qpd", "vgatherpf0qps", "vgatherpf1dpd", "vgatherpf1dps",
        "vgatherpf1qpd", "vgatherpf1qps", "vgatherqpd", "vgatherqps", "vgetexppd", "vgetexpps", "vgetexpsd",
        "vgetexpss", "vgetmantpd", "vgetmantps", "vgetmantsd", "vgetmantss", "vhaddpd", "vhaddps", "vhsubpd", "vhsubps",
        "vinsertf128", "vinsertf32x4", "vinsertf32x8", "vinsertf64x2", "vinsertf64x4", "vinserti128", "vinserti32x4",
        "vinserti32x8", "vinserti64x2", "vinserti64x4", "vinsertps", "vlddqu", "vldmxcsr", "vmaskmovdqu", "vmaskmovpd",
        "vmaskmovps", "vmaxpd", "vmaxps", "vmaxsd", "vmaxss", "vmcall", "vmclear", "vminpd", "vminps", "vminsd",
        "vminss", "vmlaunch", "vmovapd", "vmovaps", "vmovd", "vmovddup", "vmovdqa", "vmovdqa32", "vmovdqa64", "vmovdqu",
        "vmovdqu16", "vmovdqu32", "vmovdqu64", "vmovdqu8", "vmovhlps", "vmovhpd", "vmovhps", "vmovlhps", "vmovlpd",
        "vmovlps", "vmovmskpd", "vmovmskps", "vmovntdq", "vmovntdqa", "vmovntpd", "vmovntps", "vmovq", "vmovsd",
        "vmovshdup", "vmovsldup", "vmovss", "vmovupd", "vmovups", "vmpsadbw", "vmptrld", "vmptrst", "vmread",
        "vmresume", "vmulpd", "vmulps", "vmulsd", "vmulss", "vmwrite", "vmxoff", "vmxon", "vorpd", "vorps", "vpabsb",
        "vpabsd", "vpabsq", "vpabsw", "vpackssdw", "vpacksswb", "vpackusdw", "vpackuswb", "vpaddb", "vpaddd", "vpaddq",
        "vpaddsb", "vpaddsw", "vpaddusb", "vpaddusw", "vpaddw", "vpalignr", "vpand", "vpandd", "vpandn", "vpandnd",
        "vpandnq", "vpandq", "vpavgb", "vpavgw", "vpblendd", "vpblendmb", "vpblendmd", "vpblendmq", "vpblendmw",
        "vpblendvb", "vpblendw", "vpbroadcastb", "vpbroadcastd", "vpbroadcastmb2q", "vpbroadcastmw2d", "vpbroadcastq",
        "vpbroadcastw", "vpclmulqdq", "vpcmpb", "vpcmpd", "vpcmpeqb", "vpcmpeqd", "vpcmpeqq", "vpcmpeqw", "vpcmpestri",
        "vpcmpestrm", "vpcmpgtb", "vpcmpgtd", "vpcmpgtq", "vpcmpgtw", "vpcmpistri", "vpcmpistrm", "vpcmpq", "vpcmpub",
        "vpcmpud", "vpcmpuq", "vpcmpuw", "vpcmpw", "vpcompressd", "vpcompressq", "vpconflictd", "vpconflictq",
        "vperm2f128", "vperm2i128", "vpermd", "vpermi2d", "vpermi2pd", "vpermi2ps", "vpermi2q", "vpermi2w", "vpermilpd",
        "vpermilps", "vpermpd", "vpermps", "vpermq", "vpermw", "vpexpandd", "vpexpandq", "vpextrb", "vpextrd",
        "vpextrq", "vpextrw", "vpgatherdd", "vpgatherdq", "vpgatherqd", "vpgatherqq", "vphaddd", "vphaddsw", "vphaddw",
        "vphminposuw", "vphsubd", "vphsubsw", "vphsubw", "vpinsrb", "vpinsrd", "vpinsrq", "vpinsrw", "vplzcntd",
        "vplzcntq", "vpmaddubsw", "vpmaddwd", "vpmaskmovd", "vpmaskmovq", "vpmaxsb", "vpmaxsd", "vpmaxsq", "vpmaxsw",
        "vpmaxub", "vpmaxud", "vpmaxuq", "vpmaxuw", "vpminsb", "vpminsd", "vpminsq", "vpminsw", "vpminub", "vpminud",
        "vpminuq", "vpminuw", "vpmovb2m", "vpmovd2m", "vpmovdb", "vpmovdw", "vpmovm2b", "vpmovm2d", "vpmovm2q",
        "vpmovm2w", "vpmovmskb", "vpmovq2m", "vpmovqb", "vpmovqd", "vpmovqw", "vpmovsdb", "vpmovsdw", "vpmovsqb",
        "vpmovsqd", "vpmovsqw", "vpmovswb", "vpmovsxbd", "vpmovsxbq", "vpmovsxbw", "vpmovsxdq", "vpmovsxwd",
        "vpmovsxwq", "vpmovusdb", "vpmovusdw", "vpmovusqb", "vpmovusqd", "vpmovusqw", "vpmovuswb", "vpmovw2m",
        "vpmovwb", "vpmovzxbd", "vpmovzxbq", "vpmovzxbw", "vpmovzxdq", "vpmovzxwd", "vpmovzxwq", "vpmuldq", "vpmulhrsw",
        "vpmulhuw", "vpmulhw", "vpmulld", "vpmullq", "vpmullw", "vpmuludq", "vpor", "vpord", "vporq", "vprold",
        "vprolq", "vprolvd", "vprolvq", "vprord", "vprorq", "vprorvd", "vprorvq", "vpsadbw", "vpscatterdd",
        "vpscatterdq", "vpscatterqd", "vpscatterqq", "vpshufb", "vpshufd", "vpshufhw", "vpshuflw", "vpsignb", "vpsignd",
        "vpsignw", "vpslld", "vpslldq", "vpsllq", "vpsllvd", "vpsllvq", "vpsllvw", "vpsllw", "vpsrad", "vpsraq",
        "vpsravd", "vpsravq", "vpsravw", "vpsraw", "vpsrld", "vpsrldq", "vpsrlq", "vpsrlvd", "vpsrlvq", "vpsrlvw",
        "vpsrlw", "vpsubb", "vpsubd", "vpsubq", "vpsubsb", "vpsubsw", "vpsubusb", "vpsubusw", "vpsubw", "vpternlogd",
        "vpternlogq", "vptest", "vptestmb", "vptestmd", "vptestmq", "vptestmw", "vptestnmb", "vptestnmd", "vptestnmq",
        "vptestnmw", "vpunpckhbw", "vpunpckhdq", "vpunpckhqdq", "vpunpckhwd", "vpunpcklbw", "vpunpckldq", "vpunpcklqdq",
        "vpunpcklwd", "vpxor", "vpxord", "vpxorq", "vrangepd", "vrangeps", "vrangesd", "vrangess", "vrcp14pd",
        "vrcp14ps", "vrcp14sd", "vrcp14ss", "vrcp28pd", "vrcp28ps", "vrcp28sd", "vrcp28ss", "vrcpps", "vrcpss",
        "vreducepd", "vreduceps", "vreducesd", "vreducess", "vrndscalepd", "vrndscaleps", "vrndscalesd", "vrndscaless",
        "vroundpd", "vroundps", "vroundsd", "vroundss", "vrsqrt14pd", "vrsqrt14ps", "vrsqrt14sd", "vrsqrt14ss",
        "vrsqrt28pd", "vrsqrt28ps", "vrsqrt28sd", "vrsqrt28ss", "vrsqrtps", "vrsqrtss", "vscalefpd", "vscalefps",
        "vscalefsd", "vscalefss", "vscatterdpd", "vscatterdps", "vscatterpf0dpd", "vscatterpf0dps", "vscatterpf0qpd",
        "vscatterpf0qps", "vscatterpf1dpd", "vscatterpf1dps", "vscatterpf1qpd", "vscatterpf1qps", "vscatterqpd",
        "vscatterqps", "vshuff32x4", "vshuff64x2", "vshufi32x4", "vshufi64x2", "vshufpd", "vshufps", "vsqrtpd",
        "vsqrtps", "vsqrtsd", "vsqrtss", "vstmxcsr", "vsubpd", "vsubps", "vsubsd", "vsubss", "vtestpd", "vtestps",
        "vucomisd", "vucomiss", "vunpckhpd", "vunpckhps", "vunpcklpd", "vunpcklps", "vxorpd", "vxorps", "vzeroall",
        "vzeroupper", "wait", "wbinvd", "wrfsbase", "wrgsbase", "wrmsr", "wrpkru", "xabort", "xacquire", "xadd",
        "xbegin", "xchg", "xend", "xgetbv", "xlat", "xlatb", "xor", "xorpd", "xorps", "xrelease", "xrstor", "xrstors",
        "xsave", "xsavec", "xsaveopt", "xsaves", "xsetbv", "xtest"}
