version: '3.8'
services:

  malcallgraph_train:
    image: image_malcallgraph_train
    container_name: container_malcallgraph_train
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
