version: '3.8'
services:

  malflow_train:
    image: image_malflow_train
    container_name: container_malflow_train
    build:
      context: ../../../
      network: host
      dockerfile: ./core/processors/bagnet/Dockerfile
    env_file:
      - dataset.env
