name: malcallgraph-train
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - albumentations==1.3.1
  - cudatoolkit==11.8.0
  - matplotlib==3.7.2
  - numpy==1.24.3
  - pandas==1.5.3
  - pip==23.0
  - python==3.8
  - python-dotenv==0.21.0
  - scikit-learn==1.3.0
  - tensorflow==2.4.1
  - tensorflow-datasets==1.2.0
  - pip:
    - opencv-python==4.9.0.80
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.0.1+cu118
    - torchvision==0.15.2+cu118
    - torchinfo==1.8.0
