# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
        pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Cache `docker build`
      id: cache-docker-build
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}--${{ hashFiles('build/radare2-5.8.8/Dockerfile', 'Dockerfile', 'docker-compose.yml') }}
        path: ~/image_malcallgraph.tar

    - name: Building the test container - `docker build` & `docker save`
      if: ${{ steps.cache-docker-build.outputs.cache-hit != 'true' }}
      run: |
        docker compose build --no-cache malcallgraph_test
        docker save image_malcallgraph > ~/image_malcallgraph.tar

    - name: Testing
      run: |
        docker load --input ~/image_malcallgraph.tar
        docker compose up malcallgraph_test

    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.2.11
      with:
        lcov-file: ./test/coverage.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
